global.nofollow=0;
//with (oMonstar) x=xstart;
with (oMonstar) visible=1;
sFollow("delete",oFollower0);
sFollow("update");
with (oBarkley) {
sprt=sBalthios;
if (global.victorian=0) name="Balthios";
else name="Balthane";
face=2;
}
oJordan.sprt=sVarious0;oJordan.subber=6;
oJordan.y+=64;
oBarkley.x=184;
oBarkley.y=16;
oBarkley.t=2;
oPlayer.solid=0;
repeat (14) sCinema(oBarkley,"move","down",4);
sCinema(oBarkley,"catchup");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"code",cine_0334);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"dialog","Damnit, it's the Monstars! Cyberdwarf, keep going, I'll hold them off!",1);
sCinema(oFollower2,"dialog","Be careful, Balthios...",1);
sCinema(oBarkley,"dialog","Don't worry about me, just make sure Hoopz gets out okay!",1);
sCinema(oFollower2,"dialog","Right!",1);
sCinema(oFollower2,"move","right",4);
sCinema(oBarkley,"code",cine_0180);
sCinema(oBarkley,"code",cine_0178);
repeat (9) sCinema1(oFollower2,"move","right",4);
repeat (9) sCinema2(oFollower3,"move","right",4);
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"cond",cine_0101);
sCinema(oBarkley,"dialog","Monstar:\\Hahaha, you think your puny zaubers can stop us? We're the Monstars! We dominated the Space Jam! We'll crush your zaubers!");
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",.7);
sCinema(oBarkley,"dialog","Zaubers? Heh, you think you know zaubers? I'll show you zaubers...",1);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomNecronEscape;
