event_inherited();
facet=2;
option[2]="Blitz";
option[1]="Zauber";
option[0]="Counter";
optiond[0]="Counter-attack for all normal damage taken.";
optiond[1]="Conjure Zauber powers to stifle foes.";
optiond[2]="Blitz enemies with stunning moves.";
footy=30;
enemy=0;
name="Balthios";
hurts=sBBalthiosHurt;
deads=sBBalthiosDead;
defend=sBBalthiosDefend;
runs=sBBalthiosWalk;
item=sBBalthiosItem;
cele=sBBalthiosCelebrate;
_vp=3464;
_bp=200;
_power=20;
_speed=15;
_guard=20;
_brain=40;
wea="time";
/////////////
ox=x;
oy=y;
optout=0;
slide=0;
stage=0; //for meter object
wdone=0;
walk=-999;
wspd=3;
doing=-1;
onr=1; scone=-999;
rou=0;
flame=0;
ang=0;
lpd=0;
event_user(14);
prefin=-1;
instance_create(0,0,oBTinter);
image_speed=0.2;
//Info
infoh[0]="Quick Reference:";
info[0]="Action Key - Zauber Slash#Cancel Key - Stab Dash#Start Key - Zeta Scan (All Foe)#Press left or right for attack information.";
infoh[1]="Action Key - Zauber Slash";
info[1]="200% base accuracy, brain damage.#Mash the action key during travel to increase damage dealt on impact. Works well againsts foes with low brain.";
infoh[2]="Cancel Key - Stab Dash";
info[2]="200% base accuracy, physical damage.#Press the cancel key to stab dash. Press again when the symbols turn red. Works well against enemies with low guard.";
infoh[3]="Start Key - Zeta Flash";
info[3]="Slow all enemy targets.#Sets back all enemy turn counters by 20%.";
info[4]="";
infomax=3;
