with (oCuchGate) instance_destroy();
sOvar(object_index,2);
oBalthios.x=144; oBalthios.y=176; oBalthios.t=1;
oCyberdwarf.x=160; oCyberdwarf.y=192; oCyberdwarf.t=0;
oHoopz.x=176; oHoopz.y=176; oHoopz.t=3;
oBarkley.x=304+16; oBarkley.y=112; oBarkley.t=3;
sCinema(oBarkley,"code",cine_0017);
sCinema(oHoopz,"wait",1);
sCinema(oHoopz,"dialog","I wonder where dad is, he's taking a really long time.",1);
sCinema(oCyberdwarf,"dialog","He couldn't possibly have-",1);
sCinema(oBalthios,"dialog","I'm sure he's okay, Hoopz... I'm sure of it.",1);
repeat (10) sCinema(oBarkley,"move","left");
repeat (3) sCinema(oBarkley,"move","down");
sCinema(oBarkley,"code",cine_0074);
sCinema(oBarkley,"dialog","Sorry for the wait. It looks like the gate's open now.",1);
sCinema(oBalthios,"dialog","It is, but the strangest thing happened to me while I was alone. I saw this great library filled with lexicons, compendiums, and tomes about zaubers. It even held a copy of the fabled \"Zaubernomicon\", which most zauber scholars did not even believe existed. I suppose it was a reflection of my greatest desires, knowledge of zaubers, but still, it was interesting to see.",1);
sCinema(oCyberdwarf,"dialog","Something similar happened to me. I saw an illusion of myself before... before my b-ball skin grafts. I saw who I would be today if it weren't for the accident.",1);
sCinema(oBalthios,"dialog","It seems we both saw our greatest desires. Did you see anything, Hoopz?",1);
sCinema(oHoopz,"dialog","Nope, I didn't see anything.",1);
sCinema(oCyberdwarf,"dialog","A-amazing...",1);
sCinema(oBalthios,"dialog","You're sure of this, Hoopz? You saw nothing?",1);
sCinema(oHoopz,"dialog","Yeah, nothing. Not even vidcons.",1);
sCinema(oBarkley,"dialog","I, uh, didn't see anything either.",1);
sCinema(oCyberdwarf,"dialog","The implications of this... My suspicions were right all along...",1);
sCinema(oBalthios,"dialog","I believe I'm following your train of thought, Cyberdwarf, but we have more pressing things to attend to, namely the jamicite.",1);
sCinema(oCyberdwarf,"dialog","That's right, the jamicite. Let's go through the gate and get the jamicite.",1);
sCinema(oBarkley,"code",cine_0180);
sCinema(oBarkley,"code",cine_0178);
sCinema(oBarkley,"code",cine_0295);
repeat (5) sCinema(oBarkley,"move","up");
repeat (5) sCinema1(oBalthios,"move","up");
repeat (5) sCinema2(oCyberdwarf,"move","up");
repeat (5) sCinema3(oHoopz,"move","up");
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"cond",cine_0101);
sCinema(oBarkley,"cond",cine_0103);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomCuchJamicite;

