global.dieroom=RomSubwayCar0;
global.die=2;
global.diemessage="You died in the underground railroad.";
global.nofollow=1;
oCyberdwarf.x=oCyberdwarf.xstart-4;
oBalthios.x=oBalthios.xstart-4;
oCyberdwarf.t=2;
oBalthios.t=3;
oBarkley.t=2;
sOvar(object_index,1);
with (oFollower) x=-99;
sCinema(oBarkley,"dialog","Harriet Tubman:\\So, Liberty Island. I guess it's got something to do with that boy there.");
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"dialog","It's my son. Listen, can you just get us there as fast as you can?",1);
sCinema(oBarkley,"dialog","Harriet Tubman:\\Oh I could if I would. You can't rush the rails though, sonny. They don't take to that. You just gotta let em take you where they take you.");
sCinema(oBarkley,"dialog","Don't give me that-",1);
sCinema(oBarkley,"dialog","Harriet Tubman:\\Also I don't really control it, you just push this button and it goes.");
sCinema(oBarkley,"dialog","Oh... Ok.",1);
sCinema(oBarkley,"wait",2.5);
sCinema(oBarkley,"code",cine_0266);
sCinema(oBarkley,"wait",1.5);
sCinema(oBalthios,"dialog","Hmm?",1);
sCinema(oBarkley,"dialog","Harriet Tubman:\\You hear that too? Probably just a bugbear... you get those in the tunnels sometimes. Usually they don't get on board, but it's happened. Could you folks check it out for me? It's probably in one of the rear cars.");
sCinema(oBalthios,"face","right");
sCinema(oBalthios,"dialog","No problem, miss. Come on Barkley, Cyberdwarf. Let's see if we can find this bugbear.",1);
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0292);
//sCinema(oBarkley,'move','left');
//sCinema(oBarkley,'move','right');
sCinema(oBarkley,"tint",c_black,0);
