if (global.scheme[22]=1) exit;
global.dialog=1;
oBarkley.move="";
global.scheme[22]=1; 
with (oEvent1) instance_destroy();
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"dialog","What is this pool?",1);
sCinema(oHellbane,"dialog","This pool commemorates the lives of all of the ballers who were never seen again after the Great B-Ball Purge. Men like Shaquille O'Neal, Ron Artest, and even the great Hakeem Olajuwon. Although they were never found, all of their fates are almost certain...",1);
sCinema(oBarkley,"move","up",2);
sCinema(oBarkley,"move","up",2);
sCinema(oBarkley,"wait",1.3);
sCinema(oBarkley,"dialog","All of this... This is my fault. This is my fault because of the Chaos Dunk. If I were never born, these great men would have never had to-",1);
sCinema(oHellbane,"dialog","Barkley, get a hold of yourself! You can't keep blaming yourself for something that was entirely out of your control!",1);
sCinema(oBarkley,"wait",1.3);
sCinema(oBarkley,"move","down",2);
sCinema(oBarkley,"move","down",2);
sCinema(oBarkley,"wait",1.7);
sCinema(oBarkley,"dialog","The guilt I've been living with... The Chaos Dunk... Hellbane, my greatness at the one thing I loved most is what not only ruined it, but ended the lives of so many great ballers. It's like... Fate chose me to end the greatest era of man, to herald the Cyberpocalypse. When basketball died, so did the comaraderie it birthed. When basketball died, so too did the goodwill and hope that it fostered. The Great B-Ball Purge wasn't the death of basketball... It was the death of mankind.",1);
sCinema(oBarkley,"wait",2);
sCinema(oHellbane,"dialog","Something you said struck me, Barkley.",1);
sCinema(oBarkley,"dialog","What?",1);
sCinema(oHellbane,"dialog","You said that fate chose you.",1);
sCinema(oBarkley,"dialog","Yes?",1);
sCinema(oHellbane,"dialog","Maybe you're right, Barkley. Maybe fate did choose you to destroy b-ball. Maybe fate chose you to end the greatest game that mankind has ever been given. But I don't think so. I think that fate chose you for something far greater. I think fate chose you to redeem b-ball, to give it a clean slate and fresh start. Right before the purge, Barkley, b-ball lost sight of the two most important parts of the game... Slams and jams. It stopped being about the slams and instead, the neo-shekels. It stopped being about the jams and about the endorsements. I don't think of you as a devil, Charles Barkley. I think of you as an angel.",1);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","Who... Who are you?",1);
sCinema(oHellbane,"dialog","I can't tell you now but... but you will soon understand. Come on, we've got to get moving.",1);
sCinema(oBarkley,"dialog","Yeah... You're right.",1);
sCinema(oBarkley,"code",cine_0074);
