global.dieroom=RomBarkleyApart;
global.die=2;
global.diemessage="Your carelessness lead to you being knocked out. Jordan captured you, and consequently you were executed.";
oHoopz.x=-999;
if (global.plot!=3) {
global.skipper=4;
global.plot=3;
sA("stop",mSadness);
sCinema(oBarkley,"dialog","God damn I'm tired...",1);
sCinema(oBarkley,"wait",1);
repeat(12) sCinema(oBarkley,"move","up");
repeat(7) sCinema(oBarkley,"move","right");
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"face","down");
sCinema(oBarkley,"dialog","Hoopz must already be in bed. Let's see what's on TV...",1);
sCinema(oBarkley,"code",cine_0153);
sCinema(oBarkley,"dialog","The \"Ultimate Hellbane\" has struck again, this time at the Eastern Motors car company, slaying three men once again with zaubers.");
sCinema(oBarkley,"code",cine_0074);
sCinema(oBarkley,"dialog","That's it, Hoopz and I are getting the hell out of here, this place has gotten too dangerous.",1);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","Ugh,* I'm.*.*.* I'm getting tired...",1);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","Z*z*z*z*zzz....",1);
sCinema(oBarkley,"tint",c_black,0.5);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0153);
sCinema(oBarkley,"dialog","Television:\\Oh... oh my god. Man-Manhattan has just been completely destroyed. 10 million people are expected to be dead, with estimates ranging up to 15 million. Dear god, this is the most awful thing I've ever seen in my entire life... I'm... I'm sorry folks but I just wasn't prepared for this... Details are extremely limited right now but the damage was believed to have been caused by a Chaos Dunk... Yes... Yes, it has just been confirmed that the destruction was caused by a Chaos Dunk, meaning that Charles Barkley IS the perpetrator, Barkley being the only human alive capable of performing a Chaos Dunk. It... it doesn't matter if you believe in Krishna, Mohammed, or Clispaeth, now is the time to pray, Neo New York...");
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"code",cine_0074);
sCinema(oBarkley,"dialog","???:\\There he is! Get him!");
sCinema(oBarkley,"code",cine_0154);
} else {
global.firstshen=1;
global.skipper=0;
oBarkley.x=176-4;
oBarkley.y=512;
oBarkley.t=2;
with (oJordan) { x=176-4; y=560; }
with (oSoldier0) x=xstart-4; with (oSoldier1) x=xstart-4;
with (oSoldier2) x=xstart-4; with (oSoldier3) x=xstart-4;
sCinema(oBarkley,"wait",0.5);
sCinema(oJordan,"dialog","Charles Barkley, you are under arrest for performing a Chaos Dunk that killed 15 million people and associating with B.L.O.O.D.M.O.S.E.S. Give yourself up or we will be forced to terminate you.",1);
sCinema(oBarkley,"code",cine_0155);
sCinema(oBarkley,"dialog","Wh-what? What's going on? Jordan, why are you here? Where's Hoopz? What's happening?",1);
sCinema(oJordan,"dialog","You are under arrest for performing a Chaos Dunk! Surrender yourself or face the consequences!",1);
sCinema(oBarkley,"dialog","Wh-what? I didn't do a Chaos Dunk! Jordan, you know damn well I swore never to perform another Chaos Dunk 12 years ago!",1);
sCinema(oJordan,"dialog","12 years is a long enough time to change your mind. Men, arrest him!",1);
sCinema(oBarkley,"dialog","I-I didn't do it Jordan! This is a mistake! I don't know anything about B.L.O.O.D.M.O.S.E.S.",1);
sCinema(oJordan,"dialog","You're a sick, sick little man, Barkley. I gave you time to get over Maureen and b-ball, but I guess that just wasn't enough. I mean... You've got a kid, Barkley. I thought you'd grown up... Execute this bastard.",1);
sCinema(oBarkley,"dialog","You son of a bitch, Jordan!",1);
sCinema(oBarkley,"wait",0.7);
sCinema(oBarkley,"move","down",4);
sCinema(oSoldier2,"move","left",5);
sCinema(oBarkley,"quick","left");
sCinema(oBarkley,"code",cine_0156); //halts cinema on quick, is why doesnt work
sCinema2(oSoldier2,"hurt",oElectrocute,oBarkley,0);
sCinema2(oSoldier2,"wait",0.5);
sCinema(oBarkley,"code",cine_0157);
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"move","left");
sCinema(oBarkley,"quick","action");
sCinema3(oSoldier0,"face","right");
sCinema3(oSoldier2,"wait",0.3);
sCinema3(oSoldier0,"hurt",oElectrocute,oBarkley,1);
sCinema3(oSoldier2,"wait",0.5);
sCinema(oBarkley,"code",cine_0158);
sCinema(oBarkley,"cond",cine_0103);
sCinema(oBarkley,"code",cine_0159);
sCinema(oBarkley,"move","left",6);
sCinema(oBarkley,"move","down",6);
repeat(5)sCinema(oBarkley,"move","left",6);
repeat(20)sCinema(oBarkley,"move","down",6);
}
