global.plot=1;
sDialog("set",2,"center");
global.skipper=1;
sCinema(oBalthios,"face","down",4);
sCinema(oBarkley,"face","down",4);
sCinema(oBarkley,"dialog","Warning:\\The game you are about to play is canon.");
sCinema(oBarkley,"wait",3);
sCinema(oBarkley,"sound",mPart0);
sCinema(oBarkley,"dialog","The year is 2053. Basketball is dead.",2);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"create",oIntro0a);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"sound",mPart1);
sCinema(oBarkley,"dialog","My name is Charles Barkley. I am one of the last b-ball stars alive.",2);
sCinema(oBarkley,"wait",2.3);
sCinema(oBarkley,"sound",mPart2);
sCinema(oBarkley,"dialog","In 2041, basketball was made illegal and almost all b-ballers were massacred in what is now known as \"The Great B-Ball Purge\". I lived, but I lost my reason for living. B-ball was gone.",2);
sCinema(oBarkley,"user",oIntro0a);
sCinema(oBarkley,"wait",2.6);
sCinema(oBarkley,"sound",mPart3);
sCinema(oBarkley,"dialog","I live in the post-cyberpocalyptic ruins of Neo New York with my 12 year old son Hoopz. I've given him all I can but sometimes I wonder if it's enough...",2);
sCinema(oBarkley,"pan",2);
sCinema(oBarkley,"code",cine_0074);
sCinema(oHoopz,"dialog","Dad! Dad! Watch this!",1);
sCinema(oHoopz,"effect","swap",sHoopz1);
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","left");
sCinema(oHoopz,"move","left");
sCinema(oHoopz,"move","down");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","up");
sCinema(oHoopz,"move","left");
sCinema(oHoopz,"face","up");
sCinema(oHoopz,"face","right");
sCinema(oHoopz,"face","down");
sCinema(oHoopz,"face","left");
sCinema(oHoopz,"face","up");
sCinema(oHoopz,"face","right");
sCinema(oHoopz,"face","down");
sCinema(oHoopz,"face","left");
sCinema(oHoopz,"face","down");
sCinema(oHoopz,"jump","start");
sCinema(oHoopz,"jump","end");
sCinema(oHoopz,"jump","start");
sCinema(oHoopz,"jump","end");
sCinema(oHoopz,"jump","start");
sCinema(oHoopz,"move","upright");
sCinema(oHoopz,"jump","end");
sCinema(oHoopz,"jump","start");
sCinema(oHoopz,"move","left");
sCinema(oHoopz,"move","left");
sCinema(oHoopz,"jump","end");
sCinema(oHoopz,"jump","start");
sCinema(oHoopz,"move","down");
sCinema(oHoopz,"move","down");
sCinema(oHoopz,"jump","end");
sCinema(oHoopz,"jump","start");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"jump","end");
sCinema(oHoopz,"jump","start");
sCinema(oHoopz,"move","upleft");
sCinema(oHoopz,"jump","end");
sCinema(oHoopz,"face","down");
sCinema(oBalthios,"dialog","Impressive, Hoopz. Your dribbling has gotten much better in the past few weeks.",1);
sCinema(oBarkley,"code",cine_0153);
sCinema(oBarkley,"sound",mThatbal);
sCinema(oBalthios,"dialog","That's Balthios, the octoroon great grandson of Lebron James. He doesn't like to talk about himself, but he's a good guy.");
sCinema(oBarkley,"code",cine_0074);
sCinema(oHoopz,"dialog","Right dad? I've gotten better, huh dad?",1);
sCinema(oBarkley,"wait",2.4);
sCinema(oHoopz,"dialog","Dad?",1);
sCinema(oBarkley,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oBarkley,"dialog","Huh? Oh, uh. Yeah. Yeah, you've gotten a lot better, son.",1);
sCinema(oHoopz,"effect","swap",sHoopz0);
sCinema(oHoopz,"dialog","What's the matter, dad?",1);
sCinema(oBarkley,"dialog","Nothing, Hoopz. I was just... Just thinking.",1);
sCinema(oHoopz,"dialog","Thinking about b-ball, huh?",1);
sCinema(oBarkley,"wait",2.4);
sCinema(oBarkley,"dialog","Yeah, that's it... I was thinking about b-ball... Hoopz, why don't you go play some vidcons? I want to speak to Mr. James for a moment.",1);
sCinema(oHoopz,"dialog","Sure dad. Thanks for the dribbling tips and wall scrolls, Mr. James.",1);
sCinema(oBalthios,"dialog","No sweat, kid. Keep on practicing though.",1);
sCinema(oHoopz,"dialog","Sure will!",1);
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","up");
sCinema(oHoopz,"move","up");
sCinema(oHoopz,"move","up");
sCinema(oHoopz,"move","up");
sCinema(oHoopz,"move","up");
sCinema(oHoopz,"move","up");
sCinema(oHoopz,"move","up");
sCinema(oHoopz,"move","up");
sCinema(oHoopz,"move","left");
sCinema(oHoopz,"move","left");
sCinema(oHoopz,"move","up");
sCinema(oHoopz,"face","up");
sCinema(oBarkley,"face","right");
sCinema(oBalthios,"face","left");
sCinema(oBalthios,"dialog","You were thinking about her again, weren't you Charles?",1);
sCinema(oBarkley,"dialog","Hmm?",1);
sCinema(oBalthios,"dialog","Maureen. You were thinking about Maureen, weren't you?",1);
sCinema(oBarkley,"wait",2.4);
sCinema(oBarkley,"dialog","He reminds me so much of her. The way he moves, his enthusiasm for the game, his eyes...",1);
sCinema(oBarkley,"wait",1.9);
sCinema(oBalthios,"dialog","You still blame yourself for what happened.",1);
sCinema(oBarkley,"dialog","Yeah, Balthios. Yeah I do. And it won't happen ever again. I... I just can't stand knowing that all of this... everything... could be different.",1);
sCinema(oBalthios,"dialog","Barkley, you don't need to...",1);
sCinema(oBarkley,"dialog","Yeah, Balthios... I know, but I swear on her grave that nobody will ever suffer a Chaos Dunk again...",1);
sCinema(oBarkley,"code",cine_0153);
sCinema(oDummy,"pan",4);
sCinema(oBarkley,"sound",mBase);
sCinema(oBarkley,"dialog","Neo New York is a base and disgusting city...");
//sCinema(oBarkley,'effect','fadein');
sCinema(oBarkley,"code",cine_0165);
sCinema(oBarkley,"code",cine_0166);
sCinema(oBarkley,"code",cine_0167);
sCinema(oBalthios,"face","left");
