if (global.plot=0) {
oHoopz.sprt=sHoopz0;
global.camera=oDummy;
if (file_exists("victorian.txt") && global.scheme[31]=0) {
sDialog("set",1,"bottom");
sCinema(oBarkley,"dialog","Enable Victorian Steampunk Mode?",0,"Yeah","Nah");
sCinema(oBarkley,"code",cine_0160);
} else event_user(3);
} else {
oBarkley.y-=16;
global.plot=2;
global.camera=oDummy;
oHoopz.x=global.timpx;
oHoopz.y=global.timpy;
oBarkley.t=1;
oBalthios.t=3;
oHoopz.t=0;
//neo new york cinema
sCinema(oBarkley,"pan",4);
sCinema(oBarkley,"code",cine_0153);
sCinema(oBarkley,"dialog","Television:\\Breaking news just in! A killing spree has been reported...");
sCinema2(oBalthios,"move","down");
sCinema2(oBalthios,"move","right");
sCinema2(oBalthios,"move","right");
sCinema2(oBalthios,"move","right");
sCinema2(oBalthios,"move","right");
sCinema2(oBalthios,"move","right");
sCinema2(oBalthios,"move","up");
sCinema2(oBalthios,"face","down");
sCinema1(oBarkley,"move","down");
sCinema1(oBarkley,"move","right");
sCinema1(oBarkley,"move","right");
sCinema1(oBarkley,"move","right");
sCinema1(oBarkley,"move","right");
sCinema1(oBarkley,"move","right");
sCinema1(oBarkley,"move","up");
sCinema1(oBarkley,"face","down");
sCinema(oHoopz,"code",cine_0161);
sCinema(oHoopz,"code",cine_0162);
sCinema(oHoopz,"move","down");
sCinema(oHoopz,"move","down");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","right");
sCinema(oHoopz,"move","down");
sCinema(oHoopz,"move","down");
sCinema(oHoopz,"move","down");
sCinema(oHoopz,"move","down");
sCinema(oHoopz,"move","down");
sCinema(oHoopz,"move","left");
sCinema(oHoopz,"move","left");
//sCinema(oHoopz,'move','left');
sCinema(oHoopz,"face","down");
sCinema(oBarkley,"code",cine_0153);
sCinema(oBalthios,"dialog","Television:\\The cloaked octoroon, known only as \"Ultimate Hellbane\" has struck again, this time killing two men in the NNY Mall. Police reported signs of zauber use and Ultimate Hellbane is believed to have connections with the terrorist organization B.L.O.O.D.M.O.S.E.S.");
sCinema(oBarkley,"code",cine_0074);
sCinema(oBarkley,"dialog","Crime everywhere... This city is going to hell. Hoopz, I don't want you going outside tonight.",1);
sCinema(oHoopz,"dialog","Awww, dad.",1);
sCinema(oBarkley,"wait",3.3);
sCinema(oBalthios,"dialog","I... I must take my leave now.",1);
sCinema(oBalthios,"move","down");
sCinema(oBalthios,"move","down");
sCinema(oHoopz,"dialog","Bye Mr. James.",1);
sCinema(oBarkley,"wait",1.8);
sCinema(oBalthios,"dialog","...Goodbye, Hoopz.",1);
repeat(9) sCinema3(oJordan,"move","up");
sCinema(oHoopz,"code",cine_0163);
repeat(9) sCinema(oBalthios,"move","left");
//sCinema(oBarkley,'wait',4);
sCinema(oBalthios,"move","down");
sCinema(oBalthios,"move","down");
sCinema(oBalthios,"face","right");
sCinema(oBalthios,"dialog","Mr. Jordan...",1);
sCinema(oJordan,"dialog","Mr. James...",1);
sCinema4(oBalthios,"move","down");
sCinema4(oBalthios,"move","down");
sCinema4(oBalthios,"move","down");
sCinema4(oBalthios,"move","down");
sCinema4(oBalthios,"move","down");
sCinema4(oBalthios,"destroy",oBalthios);
sCinema(oHoopz,"code",cine_0164);
repeat (3) sCinema(oJordan,"move","up");
repeat (6) sCinema(oJordan,"move","right");
sCinema(oJordan,"face","up");
sCinema(oBarkley,"dialog","Jordan... What are you doing here...",1);
sCinema(oJordan,"dialog","That's a nice way to greet a friend, Charles. Heh, I was just in the neighborhood and thought I heard some... dribbling.",1);
sCinema(oBarkley,"dialog","You have absolutely no grounds to come into this house, Michael. You know that.",1);
sCinema(oJordan,"dialog","Really now? You were an all-star baller and I heard dribbling. I have every right to come in thanks to the B-ball Confiscation Act. Or are you saying I don't have that right?",1);
sCinema(oBarkley,"dialog","I'm saying you're a son of a bitch, Jordan.",1);
sCinema(oJordan,"dialog","Hahahaha! I'll play your game, Barkley. \\This time.",1);
sCinema(oBarkley,"dialog","...",1);
sCinema(oJordan,"dialog","Oh, and Hoopz.",1);
sCinema(oHoopz,"dialog","Yeah?",1);
sCinema(oBarkley,"wait",2.7);
sCinema(oJordan,"dialog","Keep practicing.",1);
repeat (6) sCinema(oJordan,"move","left");
repeat (8) sCinema(oJordan,"move","down");
sCinema(oHoopz,"dialog","......",1);
sCinema(oHoopz,"destroy",oJordan);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","Hoopz, I'm going out to get some medicine.",1);
sCinema(oHoopz,"dialog","Okay dad.",1);
sCinema(oBarkley,"wait",2);
sCinema(oHoopz,"dialog","You okay, dad?",1);
sCinema(oBarkley,"dialog","Yeah, Hoopz. I'm gonna be okay.",1);
sCinema(oHoopz,"code",cine_0014);
}


