global.skipper=11;
oFerry.image_index=1; oFerry.image_speed=0;
oWall0.solid=0;
oWall.solid=0;
with (oPlayer) solid=0;
oBalthios.sprt=sDuergar;
oCyberdwarf.visible=1;
oBalthios.visible=1;
sPos("load");
oFerry.y=global.timpy;
sOvar(object_index,2);
sOvar(oTubman,3);
sOvar(oIntro25,6);
sOvar(oFerry,2);
sParty("add",1); ////////////////here
sCinema(oSeaman,"code",cine_0441);
sCinema(oBalthios,"dialog","Duergar:\\G-guh...");
sCinema(oBalthios,"move","right",2);
sCinema(oBalthios,"dialog","Duergar:\\Guh.....");
sCinema(oBalthios,"move","right",2);
sCinema(oBalthios,"dialog","Duergar:\\GAAAAAAAH!");
sCinema(oSeaman,"code",cine_0442);
sCinema(oBalthios,"effect","swap",sBalthios);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","B-Balthios?!",1);
sCinema(oCyberdwarf,"dialog","Th-that duergar was you??",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBalthios,"face","left");
sCinema(oBalthios,"dialog","I... I am sorry Charles, Cyberdwarf. My presence has put you at risk. I was... irresponsible.",1);
sCinema(oBarkley,"dialog","Balthios?",1);
sCinema(oBalthios,"dialog","You see... long ago I was cursed by a gypsy. Every Columbus Day I am forced to turn into a rampaging duergar filled with bloodlust and disregard for those around me, entirely consumed by a hunger for rubies and gemstones. I have no control over myself and my actions and... and I regret it.",1);
sCinema(oCyberdwarf,"dialog","Why didn't you tell us, Balthios? We could have helped.",1);
sCinema(oBalthios,"dialog","I forgot how near to Columbus Day it was. I am sorry. Besides, what could you have done? The only way to remove the curse is to eradicate all gypsies. But it seems now that the curse has temporarily lifted and that I will not be plagued with the burden of duergars until next Columbus Day.",1);
repeat (1) sCinema(oSeaman,"move","down");
sCinema(oBarkley,"dialog","Captain:\\Land ho! Now approaching Liberty Island!"); //208, 112
sCinema(oSeaman,"code",cine_0443);
sCinema(oBarkley,"wait",8);
sCinema(oBarkley,"dialog","Captain:\\Here we are, anchored at Liberty Island dock.");
sCinema(oSeaman,"code",cine_0383);
repeat (6) sCinema(oSeaman,"move","down");
repeat (2) sCinema(oSeaman,"move","right");
sCinema(oSeaman,"code",cine_0444);
sCinema(oBarkley,"code",cine_0180);
sCinema(oBarkley,"code",cine_0178);
repeat (5) sCinema(oBarkley,"move","down");
repeat (6) sCinema(oBarkley,"move","right");
sCinema(oSeaman,"code",cine_0031);
repeat (4) sCinema1(oBalthios,"move","down");
repeat (1) sCinema1(oBalthios,"move","right");
sCinema1(oSeaman,"code",cine_0445);
repeat (3) sCinema2(oCyberdwarf,"move","down");
repeat (5) sCinema2(oCyberdwarf,"move","right");
sCinema2(oSeaman,"code",cine_0446);
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"cond",cine_0101);
sCinema(oSeaman,"code",cine_0447);
sCinema(oSeaman,"move","left");
sCinema(oSeaman,"move","left");
sCinema(oSeaman,"move","up");
sCinema(oSeaman,"face","left");
sCinema(oSeaman,"code",cine_0448);
repeat (3) sCinema(oBarkley,"move","left");
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"face","right");
sCinema(oBalthios,"dialog","Captain:\\I won't be taking you back. The ship was damaged while the duergar was in the hull rummaging for gemstones. I don't know why you're here but you don't look like one of those cult loonies. Take care of yourself... Charles Barkley.");
sCinema(oBarkley,"dialog","You too, old man of the sea... You too.",1);
sCinema(oSeaman,"code",cine_0449);
