//160,176
sCLevel(3);
global.skipper=6;
oVince.t=0;
oBalthios.t=0;
oBarkley.t=0;
oBarkley.x=160-4;
oBarkley.y=176;
global.nofollow=1;
global.plot=7;
with (oFollower) x=-999;
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"cond",cine_0148);
repeat (2) sCinema1(oBalthios,"move","up");
sCinema1(oBalthios,"move","right");
sCinema1(oBalthios,"face","up");
repeat (2) sCinema2(oVince,"move","up");
sCinema2(oVince,"move","left");
sCinema2(oVince,"face","up");
sCinema(oBarkley,"code",cine_0370);
repeat (3) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"dialog","???|Cyberdwarf:\\Barkley, I've been waiting for you.");
sCinema(oBarkley,"dialog","C... Cyberdwarf?",1);
sCinema(oCyberdwarf,"dialog","Cyberdwarf:\\Yes... That is I.");
sCinema(oBarkley,"wait",1.5);
sCinema(oCyberdwarf,"face","down");
sCinema(oBarkley,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oBarkley,"dialog","I...",1);
sCinema(oBalthios,"dialog","Barkley...",1);
sCinema(oCyberdwarf,"dialog","You're looking at my face, aren't you? You're wondering why I look like I do.",1);
sCinema(oBarkley,"dialog","No, it's not that-",1);
sCinema(oCyberdwarf,"dialog","I am not from here, Barkley. I am from another world, far away. A world of dwarfs.",1);
sCinema(oBarkley,"dialog","Where are you from?",1);
sCinema(oCyberdwarf,"dialog","I'm from space.",1);
sCinema(oBarkley,"dialog","Y-your face...",1);
sCinema(oBalthios,"dialog","Barkley...",1);
sCinema(oCyberdwarf,"dialog","It was the fire. I lost control of my ship upon entry of this planet's atmosphere and... the fire ravaged my ship. I will never be able to go home now, but even more, it ravaged my body. Someone found me and took me to the hospital, but it was no use. The fire had destroyed my flesh and the hospital had no cyberdwarf skin. All they had were b-balls.",1);
sCinema(oBarkley,"dialog","They were forced to graft b-balls to your skin...",1);
sCinema(oCyberdwarf,"dialog","Yes. I have flesh of... of b-balls now.",1);
sCinema(oBarkley,"dialog","I am sorry, Cyberdwarf...",1);
sCinema(oCyberdwarf,"dialog","There are more important things to be sorry about, like your father's predicament, Barkley.",1);
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"dialog","My... father?",1);
sCinema(oCyberdwarf,"dialog","Balthios, this is Barkley, isn't it? Hoopz Barkley?",1);
sCinema(oBalthios,"dialog","N-no, Cyberdwarf. This is Charles, Hoopz's father! I thought you wanted me to bring Charles!",1);
sCinema(oCyberdwarf,"dialog","Damnit Balthios, I said Hoopz! Charles is not the one!",1);
sCinema3(oVince,"move","down",1.1);
sCinema3(oVince,"move","up",1.1);
sCinema3(oVince,"move","up",1.1);
sCinema3(oVince,"move","left",1.1);
sCinema3(oVince,"move","down",1.1);
sCinema3(oVince,"move","right",1.1);
sCinema3(oVince,"move","up",1.1);
sCinema3(oVince,"move","right",1.1);
sCinema3(oVince,"face","up",1.1);
sCinema(oBarkley,"face","left");
sCinema(oBalthios,"face","left");
sCinema(oBarkley,"code",cine_0295);
sCinema(oVince,"dialog","Bzzt! Zzzt! The... one... Zzzt! Bzzt!",1);
sCinema(oBarkley,"cond",cine_0103);
sCinema(oBalthios,"dialog","Vinceborg 2050, what's happening?",1);
sCinema(oVince,"dialog","N-nothing Balthios... I thought I was getting back my memories but it was... nothing.",1);
sCinema(oBarkley,"face","up");
sCinema(oBalthios,"face","up");
sCinema(oCyberdwarf,"dialog","Balthios, this grave error has cost us what precious little time to spare we had. We must find Hoopz Barkley at once!",1);
sCinema(oBarkley,"dialog","Wh-what's happening? What are you talking about?",1);
sCinema(oCyberdwarf,"dialog","There is no time to explain! Where is Hoopz?",1);
sCinema(oBalthios,"dialog","He's at the church. I left him with Bird.",1);
sCinema(oCyberdwarf,"dialog","Then we must go there at once! I will explain everything once he is in our protection, but there is no time to spare and too much to lose if we wait any further. There is a passage to the church if we take the path to the north and left. Quickly, we must make haste!",1);
sCinema(oBarkley,"dialog","Balthios, what's happening? Is Hoopz going to be okay?",1);
sCinema(oBalthios,"dialog","I... don't know, Barkley. Only time can tell.",1);
sCinema(oBarkley,"dialog","Only time can tell...",1);
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0371);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"tint",c_black,0);
sCinema(oBarkley,"code",cine_0074);
sCinema(oBarkley,"code",cine_0372);
sCinema(oBarkley,"code",cine_0373);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"dialog","Cyberdwarf has joined the party!");
