//144,160
//160,144 bark
sCLevel(4);
oHoopz.t=3;
oCyberdwarf.t=2;
oBalthios.t=0;
oBarkley.t=0;
oBarkley.x=160-4;
oBarkley.y=144;
oBalthios.x=144-4;
oBalthios.y=160;
global.nofollow=1;
with (oFollower) x=-999;
if (global.plot=9) {
global.cinema=0;
global.freeze=0;
sCinema(oBarkley,"code",cine_0368);
sCinema(oBarkley,"code",cine_0006);
sCinema(oBarkley,"dialog","Hoopz has joined the party!");
exit;
}
global.skipper=7;
global.plot=9;
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"cond",cine_0148);
sCinema(oHoopz,"dialog","Mr. Jordan was... he was gonna hurt me dad, wasn't he?",1);
sCinema(oBarkley,"dialog","Yes, son. He would have hurt you if we didn't get there in time.",1);
sCinema(oHoopz,"dialog","But what did I do?",1);
sCinema(oBalthios,"dialog","You didn't do anything, Hoopz. Mr. Jordan is... he's not a well man. He's doing things he knows he shouldn't.",1);
sCinema(oCyberdwarf,"dialog","That's right, Hoopz. But we're not going to let him do anything to you.",1);
sCinema(oBarkley,"wait",1.4);
sCinema(oBarkley,"dialog","You said you'd clear this all up when we got Hoopz, Cyberdwarf. Tell me what the hell is going on.",1);
sCinema(oCyberdwarf,"dialog","The Chaos Dunk that destroyed Manhattan... It was B.L.O.O.D.M.O.S.E.S. Somehow they got their hands on the Ultimate B-Ball-",1);
sCinema(oHoopz,"dialog","The Ultimate B-Ball?",1);
sCinema(oBarkley,"dialog","A long time ago, before you were even born, I was trapped in a basketball with a couple other ballers. You remember when I told you about this, right Hoopz?",1);
sCinema(oHoopz,"dialog","Yeah, the Space Jam. I remember. But what's that got to do with this?",1);
sCinema(oCyberdwarf,"dialog","Although you were no longer trapped in the Ultimate B-Ball, Barkley, its power slowly continued to grow until it rivalled its original power. Somehow, and I don't know how, the terrorist organization B.L.O.O.D.M.O.S.E.S. got their hands on the ball. I don't know what they are planning on doing with it, but from what they've shown us already, they are incredibly powerful and know how to use it.",1);
sCinema(oBarkley,"dialog","But... But who is B.L.O.O.D.M.O.S.E.S.?",1);
sCinema(oCyberdwarf,"dialog","I don't know who the leader is, but I do know that they've existed for almost a century. I think Balthios knows more than I do.",1);
sCinema(oBalthios,"dialog","No, Cyberdwarf... I don't.",1);
sCinema(oBarkley,"dialog","What do you mean?",1);
sCinema(oBalthios,"dialog","They... they killed my great grandfather, Lebron. He was killed before the Purge. They shot him, Charles. Right in the heart. I was at his deathbed when he told me about the zaubers. I... I didn't know about the James legacy, that my family was the last to harness the power of the zaubers. He told me to respect and master the zaubers, but never to use them for an ill purpose. That's why B.L.O.O.D.M.O.S.E.S. killed him, they wanted the power of the zaubers for themselves. I've been tracking them down since Lebron died but...",1);
sCinema(oCyberdwarf,"dialog","He's been chasing smoke. He can't find anything.",1);
sCinema(oBarkley,"dialog","I'm... I'm sorry Balthios. I didn't know...",1);
sCinema(oBalthios,"dialog","You have nothing to be sorry for, Barkley.",1);
sCinema(oBarkley,"wait",1.4);
sCinema(oBarkley,"dialog","So what do we do now?",1);
sCinema(oCyberdwarf,"dialog","There are two things, Barkley. Find out what B.L.O.O.D.M.O.S.E.S. is planning and stop them.",1);
sCinema(oBarkley,"dialog","Well how are we going to do that?",1);
sCinema(oCyberdwarf,"dialog","We'll need to... forge a new Ultimate B-Ball. One powerful enough to counter whatever B.L.O.O.D.M.O.S.E.S. is planning. I don't know how we'll do this, but I think we can find clues in the old Spalding building.",1);
sCinema(oBarkley,"dialog","Where's that?",1);
sCinema(oCyberdwarf,"dialog","It's located farther underground, in Proto Neo New York.",1);
sCinema(oBarkley,"move","right");
sCinema(oBarkley,"dialog","(Proto Neo New York...)",1);
sCinema(oBarkley,"wait",0.5);
sCinema(oBalthios,"dialog","So, how do we get there, Cyberdwarf?",1);
sCinema(oCyberdwarf,"dialog","We'll exit the town at the north and then take a right. After that it's just a bit farther through the sewers. There's a ladder there we can use that descends all the way down into Proto Neo New York. And that's where we'll find it. The Spalding Factory.",1);
sCinema(oBarkley,"dialog","I... I don't know where all this is leading but... but this can't be anything other than fate.",1);
sCinema(oCyberdwarf,"dialog","F.A.T.E...",1);
sCinema(oBalthios,"dialog","We should get all the supplies we need here in Cesspool X, and then we'll take off.",1);
sCinema(oBarkley,"dialog","Good idea.",1);
sCinema(oBarkley,"code",cine_0369);
sCinema(oBarkley,"code",cine_0006);
sCinema(oBarkley,"dialog","Hoopz has joined the party!");
