//Lebron Cinema
sBoss("oBBallmonster");
with (oWall0) solid=0;
oBaller.visible=1;
global.nofollow=1;
global.plot=5;
with (oFollower) x=-999;
oHellbane.visible=1;
oHellbane.x=144;
oHellbane.y=256;
oHellbane.t=0;
oBarkley.x=144;
oBarkley.y=256+16;
oBarkley.t=0;
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"cond",cine_0148);
sCinema(oBarkley,"code",cine_0357);
sCinema(oHellbane,"dialog","This is it, Barkley. This is where I wanted to take you.",1);
repeat(4) sCinema1(oHellbane,"move","up");
sCinema1(oHellbane,"move","left");
sCinema1(oHellbane,"move","up");
sCinema1(oHellbane,"face","down");
sCinema(oBarkley,"code",cine_0178);
repeat(4) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"dialog","Wh-what is this place?",1);
sCinema(oHellbane,"dialog","A sacred baller tomb... Hold on, Barkley, he's coming through!",1);
sCinema(oBarkley,"code",cine_0358);
sCinema(oBarkley,"dialog","Huh!? Hellbane! Who's he?!",1);
sCinema(oBarkley,"wait",1.5);
repeat(6) sCinema(oBaller,"move","down",8);
repeat(3) sCinema(oBaller,"move","right",8);
repeat(5) sCinema(oBaller,"move","down",8);
repeat(3) sCinema(oBaller,"move","left",8);
repeat(3) sCinema(oBaller,"move","up",8);
repeat(1) sCinema(oBaller,"move","right",8);
repeat(2) sCinema(oBaller,"move","down",8);
repeat(1) sCinema(oBaller,"move","left",8);
repeat(1) sCinema(oBaller,"move","up",8);
repeat(2) sCinema(oBaller,"move","left",8);
repeat(2) sCinema(oBaller,"move","up",8);
repeat(2) sCinema(oBaller,"move","right",8);
repeat(2) sCinema(oBaller,"move","down",8);
repeat(2) sCinema(oBaller,"move","left",8);
repeat(2) sCinema(oBaller,"move","up",8);
repeat(2) sCinema(oBaller,"move","right",8);
repeat(2) sCinema(oBaller,"move","down",8);
sCinema(oBaller,"face","down");
sCinema(oBarkley,"code",cine_0359);
sCinema(oBarkley,"wait",1);
sCinema(oHellbane,"dialog","???:\\...");
sCinema(oBarkley,"wait",0.5);
sCinema(oHellbane,"dialog","This is the tomb of my great grandfather... Lebron James.",1);
sCinema(oBarkley,"dialog","Ultimate Hellbane! That means you're...",1);
sCinema(oHellbane,"effect","swap",sBalthios);
if (global.victorian=0) sCinema(oBarkley,"code",cine_0360);
else sCinema(oBarkley,"code",cine_0361);
sCinema(oHellbane,"dialog","Yes, that's right. I'm Balthios.",1);
sCinema(oBarkley,"wait",1.8);
sCinema(oBarkley,"dialog","Wh-why didn't you tell me Balthios? If I had known...",1);
sCinema(oHellbane,"dialog","I didn't think you could handle it Barkley. People say I'm B.L.O.O.D.M.O.S.E.S., that I'm a terrorist and a murderer. I couldn't let my best friend think that of me... But that's not why I brought you here. I want you to meet... My great grandfather.",1);
sCinema(oBaller,"move","down");
sCinema(oBaller,"dialog","Charles...",1);
sCinema(oBarkley,"dialog","Lebron! What... What happened? I haven't seen you since the purge.",1);
sCinema(oBaller,"dialog","That... seems like so long ago, Charles. I don't have much time left. I can feel the doors of the B-Ball Dimension slowly closing so I must speak quickly. Listen carefully Barkley, I will only be able to tell you this once.",1);
sCinema(oBarkley,"dialog","Okay Lebron.",1);
sCinema(oBaller,"dialog","Dark forces are at foot, Charles. The terrorist organization B.L.O.O.D.M.O.S.E.S. has some sort of power... Something I... can't quite explain. I am not sure of the nature of this power but I am certain it is profoundly powerful... more powerful than anything this world has ever experienced. You recall the... Space Jam, don't you, Barkley?",1);
sCinema(oBarkley,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oBarkley,"dialog","The Space Jam? What's that got to do with it?",1);
sCinema(oBaller,"dialog","I cannot be certain, Charles, but I believe that B.L.O.O.D.M.O.S.E.S. has obtained the Ultimate B-Ball, the ball that you and the four other ballers were trapped in, and are using it to... I'm not sure, Barkley. I cannot understand the purposes of a madman, but I can only see evil coming of it.",1);
sCinema(oBarkley,"dialog","But... the Ultimate B-Ball lost its powers when Jordan won the Space Jam.",1);
sCinema(oBaller,"dialog","That is what I believed as well. It seems, though that some of your power was trapped inside the ball and grew over time; grew to a point that even the Chaos Dunk is usable. Barkley... If there are madmen out there with the ability to use the Chaos Dunk, think of all the people at risk. Think of all the people that have already died because of them. Manhattan is destroyed!",1);
sCinema(oBarkley,"dialog","No... I vowed long ago that nobody would ever suffer another Chaos Dunk. Something has to be done... anything. But Lebron, what can we do?",1);
sCinema(oBaller,"dialog","M... My time is... fa...ding... I can no l...onger... maintain... the connection.. from the B-Ball Di...mension... L...ook... to the... Cyberdwarf... Look to... the... Cy...ber...dwarf..............",1);
sCinema(oBaller,"effect","swap",sNull);
sCinema(oBarkley,"tint",c_white,1);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"tint",c_white,0);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"tint",c_white,1);
sCinema(oBarkley,"code",cine_0362);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"tint",c_white,0);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"dialog","Goodbye, Lebron...",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oHellbane,"dialog","Barkley, I can hear rumbling.",1);
sCinema(oBarkley,"code",cine_0363);
sCinema(oBarkley,"dialog","What the hell is that?",1);
sCinema(oBarkley,"code",cine_0364);
sCinema(oHellbane,"dialog","Look out! Here comes a B-Ball Monster!",1);
sCinema(oBarkley,"code",cine_0365);
sCinema(oBarkley,"wait",2);
sCinema(oHellbane,"face","right");
sCinema(oBarkley,"face","right");
sCinema(oHellbane,"dialog","B-Ball Monster:\\B-BAAAAAALLLLLLLSSSSS!");
sCinema(oBarkley,"code",cine_0366);
sCinema(oBarkley,"code",cine_0006);
sA("stopall");
sA("loop",mSpirit);
