x-=999;
stage=0;
global.dialog=1;
oBarkley.move="";
//sOvar(object_index,1);
sCinema(oJamal,"jump","start");
sCinema(oJamal,"jump","end");
sCinema(oBarkley,"dialog","Jamal Bloodguzzle:\\No! We demand the right to rubies and gemstones! Gilded treasure is a part of the Duergar heritage, that's something you can't take away from us. Glittering goblets and chalices are one thing, but rubies and gemstones... unforgivable.",0);
sCinema(oMuhammed,"jump","start");
sCinema(oMuhammed,"jump","end");
sCinema(oBarkley,"dialog","Mohammed Geniebane:\\I'm sorry but studies have proven that rubies and gemstones promote laziness in the workplace and minimize efficiency. Square Enix Goya wants to ensure maximum efficiency and quality in the mining of all chups.",0);
sCinema(oBarkley,"dialog","Jamal Bloodguzzle:\\That's ridiculous! Rubies and gemstones are the essence of Duergars. A Duergar without a dazzling ruby is like a genie without a lamp.",0);
sCinema(oBarkley,"dialog","Mohammed Geniebane:\\That... that was uncalled for.",0);
sCinema(oFollower2,"dialog","What's going on here!",1);
repeat (2) sCinema(oBarkley,"move","up");
repeat (5) sCinema(oBarkley,"move","right");
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"catchup");
sCinema(oBarkley,"dialog","Mohammed Geniebane:\\We're discussing the terms of the Duergar's return to work from stri-",0);
sCinema(oBarkley,"dialog","Jamal Bloodguzzle:\\You're Charles Barkley, aren't you?",0);
sCinema(oBarkley,"dialog","Now look, I don't want to get involved in none of this malarky. I've got nothing to do with magic lamps and gemstones.",1);
sCinema(oBarkley,"dialog","Jamal Bloodguzzle:\\Wait, wait, I think we need the input of a third party on this issue, someone who is already an established member of the community.",0);
sCinema(oBarkley,"dialog","Mohammed Geniebane:\\What are you implying, Chief Bloodguzzle?",0);
sCinema(oBarkley,"dialog","Jamal Bloodguzzle:\\That because Charles Barkley is a third party that represents the interests of neither of us, he would be able to more effectively negotiate the terms for our return to work at the Chup Mines.",0);
sCinema(oBarkley,"dialog","Look, I said I don't want nothing to do-",1);
sCinema(oFollower3,"dialog","Dad, this is your chance to do something really good for the world. You have the chance to make someone's life better.",1);
sCinema(oFollower2,"dialog","You've got the chance to give back to the dwarfs after all they've given to you, Barkley.",1);
sCinema(oBarkley,"dialog","Mohammed Geniebane:\\You've got the chance to serve your country and Square Enix Goya.",0);
sCinema(oFollower3,"dialog","Dad... I believe in you. I know deep down you know what's right and what to do.",1);
sCinema(oBarkley,"dialog","Jamal Bloodguzzle:\\So will you do it? Will you mediate for the Declaration of Duergar Rights?",0);
sCinema(oBarkley,"dialog","Mediate for civil rights negotiation?",0,"Yeah.","Nah.");
sCinema(oBarkley,"code",cine_0140);
//sCinema(oBarkley,'code',cine_0144);
