cou-=global.rd;
if (sOvar(oCuchCyber1,-1)!=1) exit;
if (global.did_action=0 || cou>0) exit;
cou=7;
xx=oBarkley.x+12;
yy=oBarkley.y+24;
spx=3;
spd=5;
spf=7;
spv=9;
if (oBarkley.t=0) {
modd=90;
} else if (oBarkley.t=1) {
modd=0;
} else if (oBarkley.t=2) {
modd=270;
} else if (oBarkley.t=3) {
modd=180;
}
repeat (30) {
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=3+random(9);
sand.direction=modd-40+random(80);
}
exit;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spx;
sand.direction=modd;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spx;
sand.direction=modd+30;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spx;
sand.direction=modd-30;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spd;
sand.direction=modd;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spd;
sand.direction=modd+30;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spd;
sand.direction=modd-30;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spf;
sand.direction=modd;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spf;
sand.direction=modd+15;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spf;
sand.direction=modd-15;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spf;
sand.direction=modd+45;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spf;
sand.direction=modd-45;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spv;
sand.direction=modd;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spv;
sand.direction=modd+15;
sand=instance_create(xx,yy,oCuchCyber0);
sand.speed=spv;
sand.direction=modd-15;
