sPos("load");
global.skipper=10;
sOvar(oJuwanna,1);
sOvar(oIntro20,2);
with (oFollower) x=-999;
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","Scott H. Creelman:\\I... I knew you were worthy, Charles... I knew you were the one to wield the Hell B-ball.");
sCinema(oBarkley,"item","Prototype B-ball",1);
sCinema(oBarkley,"dialog","I'm sorry, Creelman. I didn't want this to happen.",1);
sCinema(oBarkley,"dialog","Scott H. Creelman:\\S-sorry? You can never be sorry, Barkley. Never. Take the prototype and recharge it. Only then can you finally defeat B.L.O.O.D.M.O.S.E.S.");
sCinema(oFollower0,"dialog","Recharge it?",1);
sCinema(oBarkley,"dialog","Scott H. Creelman:\\Yes. The... the jamicite... it needs the... jam...i...cite...");
sCinema(oBarkley,"tint",c_white,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0233);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"tint",c_white,0);
sCinema(oBarkley,"dialog","He... he's gone.",1);
sCinema(oFollower2,"dialog","He's passed on, Barkley. He was waiting for this for a long time, I think.",1);
sCinema(oBarkley,"face","down");
sCinema(oBalthios,"face","right");
sCinema(oCyberdwarf,"face","right");
sCinema(oHoopz,"face","left");
sCinema(oBarkley,"dialog","So what do we do now? We've got the prototype.",1);
sCinema(oFollower2,"dialog","We're going to need to recharge it, like Creelman said. That'll probably mean we have to go to Cuchul-",1);
sCinema(oBarkley,"code",cine_0234);
sCinema(oBarkley,"cond",cine_0235);
sCinema(oFollower3,"dialog","AHHHHH!",1);
sCinema(oBarkley,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oBarkley,"dialog","Hoopz!",1);
sCinema(oBarkley,"code",cine_0236);
sCinema(oJordan,"dialog","Hahahaha! You fools, you fell for my booby trap!",1);
sCinema(oBalthios,"face","down");
sCinema(oCyberdwarf,"face","down");
//sCinema(oHoopz,'face','down');
sCinema(oBarkley,"code",cine_0237);
sCinema(oJordan,"pan",8);
sCinema(oBarkley,"dialog","Damnit, this was all just a gatdam booby trap! Jordan, you motherfucking baka, you sick motherfucking goddamn BAKA! What the fuck did you do to Hoopz? What the fuck did you do to my son?!",1);
repeat (6) sCinema(oJordan,"move","up",6);
sCinema(oBarkley,"code",cine_0238);
sCinema(oJordan,"dialog","Ahaha, don't worry Barkley, he's not dead... yet. I shot a dart filled with type 2 diabetes into him, the kind they were never able to cure. He'll be stone cold dead if you don't find a way to cure him in the next hour. Oh, but I guess that would require you to have a PhD in diabetes and not b-ball. Hahahahaha!",1);
sCinema(oBarkley,"dialog","Jordan, you sick son of a bitch! Why the fuck would you do this to a little boy!? What the hell has he ever done to you!? You goddamn baka, come on and face me!",1);
sCinema(oJordan,"dialog","Do you really think you have the time for that right now, Barkley? If I were you, I'd be saying my last farewells to Hoopz.",1);
sCinema(oFollower0,"dialog","Jordan, you...",1);
sCinema(oJordan,"dialog","Ahaha! I'll see you later! Oh, but not all of you!",1);
sCinema(oBarkley,"pan",8);
repeat (10) sCinema(oJordan,"move","down",8);
sCinema(oBarkley,"move","down");
sCinema(oBarkley,"dialog","Damnit! Hoopz, can you hear me?! Hoopz!?",1);
sCinema(oBalthios,"face","right");
sCinema(oFollower0,"dialog","Nothing...",1);
sCinema(oCyberdwarf,"face","right");
sCinema(oFollower2,"dialog","It's type 2 diabetes, Barkley. Not even I can heal it...",1);
sCinema(oBarkley,"dialog","DAMNIT! DAMNIT ALL TO HELL! Hoopz, hang in there...",1);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomProtoJuwanna;
sA("stopall");sA("loop",mParade);
