if (sOvar(object_index,-1)=1) exit;
global.dialog=1;
oBarkley.move="";
sOvar(object_index,1);
repeat (3) sCinema(oBarkley,"move","up");
sCinema(oFollower2,"dialog","The Spalding Factory... Who knows what lurks in these halls.",1);
sCinema(oBarkley,"dialog","What are these?",1);
repeat (2) sCinema(oBarkley,"move","right");
sCinema(oBarkley,"face","up");
sCinema(oFollower0,"dialog","They still appear to be functioning, even after all these years.",1);
repeat (4) sCinema(oBarkley,"move","left");
sCinema(oBarkley,"face","up");
sCinema(oFollower0,"dialog","Computer:\\Current lift status: inactive. Please insert red key.");
sCinema(oBarkley,"dialog","Lift status? Is this a fucking vidcon or something?",1);
sCinema(oFollower3,"dialog","It probably means there's a lift somewhere that's not working. We've probably gotta put in the red key to get it moving.",1);
sCinema(oBarkley,"dialog","How'd you figure that out, Hoopz?",1);
sCinema(oFollower3,"dialog","Vidcons, dad!",1);
sCinema(oBarkley,"dialog","Vidcons...",1);
sCinema(oFollower0,"dialog","We need to get moving, Charles.",1);
sCinema(oBarkley,"dialog","Alright. Let's see what we can find in this factory...",1);
repeat (2) sCinema(oBarkley,"move","right");
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"code",cine_0069);
sCinema(oBarkley,"code",cine_0006);
