if (global.scheme[26]=1) exit;
sCLevel(2);
global.dialog=1;
global.scheme[26]=1; 
sCinema(oBarkley,"dialog","???|Vinceborg:\\BLEEP BLOOP BLIP BLIP!");
sCinema(oBarkley,"dialog","What the hell is this? It looks like some kind of robot or something.",1);
sCinema(oFollower0,"dialog","I can't tell if it's functioning properly or if it's just making noises.",1);
sCinema(oBarkley,"dialog","Yeah, let's leave this hunk of scrap metal and keep going.",1);
sCinema(oBarkley,"move","down");
sCinema(oBarkley,"dialog","???|Vinceborg:\\Correction: I am a cyborg!");
sCinema(oBarkley,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"dialog","What!?",1);
sCinema(oBarkley,"dialog","???|Vinceborg:\\You said that I was a robot. I corrected you, I am a cyborg! My name is... Scanning memory chip for name... Error: cannot find name.");
sCinema(oBarkley,"dialog","Hmmm... Well your jersey has the number 15 on it. That was Vince Carter's number.",1);
sCinema(oFollower0,"dialog","You also resemble Vince, except for the metal and circuitry all over your body. But... He was lost in the Purge...",1);
sCinema(oFollower0,"dialog","???|Vinceborg:\\Scanning memory banks for Vince Carter... Yes, my name is Vinceborg 2050. I was created in 2050 to... to... Encountered error number X114JAM9, cannot remember purpose. I am Vinceborg 2050 and my mission is... nothing.");
sCinema(oFollower0,"dialog","My god! This IS Vince Carter! Vince! Vince! Do you remember me? It's me, Balthios James, the octoroon great grandson of Lebron James! Vince, tell me if you remember me!",1);
sCinema(oVince,"dialog","Processing: Balthios James...\\...\\...\\Found match! Yes Balthios, I remember you! On the day you were born, your grandfather slam dunked you and said that you would go on to be a great man. You were a child when I balled for the Nets. Nets... Nets... That is correct! I used to be a baller! I played for the New Jersey Nets!",1);
sCinema(oBarkley,"dialog","A-amazing! He is regaining his memory! Vinceborg, do you remember me? I'm Charles Barkley.",1);
sCinema(oVince,"dialog","Charles... Barkley...\\Entry found. One of the greatest slammers to have ever lived, although his jams were a little lacking. He was also one of my... Best friends.",1);
sCinema(oBarkley,"dialog","Vince, it's really you! I can't believe it! I thought you were lost in the Purge!",1);
sCinema(oVince,"dialog","Purge... the... Great B-ball Purge... Yes, I remember now, I died in the Purge but... Yes, I was rebuilt by someone. Someone... rebuilt me.",1);
sCinema(oBarkley,"dialog","Who rebuilt you? Who brought you back to life, Vince?",1);
sCinema(oVince,"dialog","I... do not... remember.",1);
sCinema(oBarkley,"dialog","Vinceborg, you have to come with us until you remember.",1);
sCinema(oVince,"dialog","Yes... I will come with you, Charles. I must remember...",1);
//
sCinema(oBarkley,"code",cine_0487);
sCinema(oBarkley,"code",cine_0373);
sCinema(oBarkley,"dialog","Vinceborg has joined the party!");
