global.nofollow=1;
with (oFollower) x=-999;
oShadowBarkley.t=0;
oBarkley.t=0;
oHoopz.t=0;
oBalthios.t=0;
oCyberdwarf.t=0;
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0345);
sCinema(oBarkley,"code",cine_0180);
sCinema(oBarkley,"code",cine_0178);
sCinema(oBarkley,"code",cine_0295);
repeat (3) sCinema(oBarkley,"move","up");
repeat (3) sCinema1(oBalthios,"move","up");
repeat (3) sCinema2(oCyberdwarf,"move","up");
repeat (3) sCinema3(oHoopz,"move","up");
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"cond",cine_0101);
sCinema(oBarkley,"cond",cine_0103);
sCinema(oBarkley,"wait",2);
sCinema(oHoopz,"dialog","Is this... the Ultimate B-Ball?",1);
sCinema(oBarkley,"dialog","???|Shadow Barkley:\\Hahaha, I see you are very astute, Hoopz Barkley, perhaps moreso than your father!");
sCinema(oBalthios,"dialog","...who are you?",1);
sCinema(oBarkley,"dialog","Tell me who the hell you are before I dunk you into oblivion.",1);
sCinema(oBarkley,"dialog","???|Shadow Barkley:\\You don't... remember me?");
sCinema(oBarkley,"dialog","What?",1);
sCinema(oBarkley,"dialog","???|Shadow Barkley:\\Charles, I am...");
sCinema(oBarkley,"wait",1.5);
sCinema(oShadowBarkley,"face","down");
sCinema(oBarkley,"wait",.5);
sCinema(oShadowBarkley,"dialog","...you.",1);
sCinema(oCyberdwarf,"dialog","By Clispaeth...",1);
sCinema(oBarkley,"dialog","What the hell is going on here?! Who the hell are you?!",1);
sCinema(oShadowBarkley,"dialog","Surely you remember the Space Jam, Charles Barkley. That is when I was born, although I have pondered more than once if I existed even before then. You see, I am a manifestation of your sub- conscious, of your dark thoughts and emotions. When you were released from the Ultimate B-Ball by Michael Jordan and the Looney Tunes, I remained behind, my power culminating over the years until I was strong enough to control the powers of the Ultimate B-Ball. Heh, when Jordan said you were the one who performed the Chaos Dunk on Manhattan, he wasn't entirely wrong.",1);
sCinema(oBarkley,"dialog","N-no... no, this can't be.",1);
sCinema(oHoopz,"dialog","Dad...",1);
sCinema(oBalthios,"dialog","This is unbelievable...",1);
sCinema(oShadowBarkley,"dialog","Ah, but none of that really matters. You got here just in time. You see, Manhattan was just a "+"\"pre-season warmup\""+" as you might have called it, Barkley. Tonight, I will harness the power of the Ultimate B-Ball and cleanse the entire world with one final Chaos Dunk. There will be no survivors.",1);
sCinema(oCyberdwarf,"dialog","But... but that's mad! Why would you ever do something like that!?",1);
sCinema(oShadowBarkley,"dialog","Hahaha, why don't you ask Charles? After all, I'm merely a manifestation of his own thoughts.",1);
sCinema(oBarkley,"dialog","N-no... I don't believe any of this... this can't be true.",1);
repeat (4) sCinema(oShadowBarkley,"move","left");
sCinema(oShadowBarkley,"dialog","B-ball has become... convoluted. Charles and I, we wanted to take the game to the next level, we wanted to take the game so much farther and when we tried, the world didn't only backlash against b-ball, but they got rid of it outright. They weren't ready for what we wanted to do with the game. They were too stupid and cowardly to accept the game's full potential. They weren't good enough for it. If I destroy all of mankind, I can begin anew a world of b-ball based on my prototype Charles Barkley.",1);
sCinema(oBalthios,"dialog","What, so we're all just a bunch of sub-humans not good enough for you?",1);
sCinema(oShadowBarkley,"dialog","Sub-humans? No, I do not believe you are sub-human. I believe you are merely human and that is the downfall of your species. Instead of welcoming the next generation, you supress it. I represent something far greater than yourself, something greater even than b-ball. I represent the post-human. What do you say, Barkley? Shall we start a new, glorious age of b-ball or shall we let it stagnate and die in the current world? Will you join me?",1);
sCinema(oHoopz,"dialog","Don't do it, dad...",1);
sCinema(oCyberdwarf,"dialog","Think of all that B.L.O.O.D.M.O.S.E.S. has done, Charles...",1);
repeat (4) sCinema(oShadowBarkley,"move","right");
sCinema(oShadowBarkley,"face","down");
sCinema(oBalthios,"dialog","The choice is yours, Barkley. This is your journey, not mine.",1);
sCinema(oBarkley,"dialog","What will you do?",0,"I will join you.","No way in hell!");
sCinema(oBarkley,"code",cine_0346);
sA("stopall");
sA("loop",mChurch);
