sOvar(object_index,1);
oRaffle.t=0;
repeat (3) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Hey, you there. Do you know any old men?",1);
sCinema(oRaffle,"move","up",6);
sCinema(oRaffle,"face","down");
sCinema(oBarkley,"dialog","???:\\Step away! Who sent you? I have a flask full of sugar water and I will not hesitate to use it!",0);
sCinema(oBarkley,"dialog","Whoa, hold on! I don't got any gripes with you pal, I'm just here looking for an old man. I was told he could cure diabetes.",1);
sCinema(oBarkley,"dialog","???:\\Is that so? Then you're not of them...",0);
sCinema(oBarkley,"dialog","Look, I don't know what's going on here. I'm not sure I want to know. All I want is for my son to be cured so I can be on my way.",1);
sCinema(oBarkley,"dialog","???:\\If only things were that simple. However, it appears with some cooperation we could mutually achieve our goals. The name is Rutherford. You would be?",0);
sCinema(oBarkley,"dialog","Charles Barkley. So do you know who this old man is? Can he really help my son?",1);
sCinema(oBarkley,"dialog","Rutherford:\\Indubitably. The man you seek is Yelmirb, but your primary concern is accessing his quarters.",0);
sCinema(oBarkley,"dialog","What do you mean?",1);
sCinema(oBarkley,"dialog","Rutherford:\\He is locked away in Liberty Tower. You may only enter with posession of the Palladium Orb Sceptre.",0);
sCinema(oBarkley,"dialog","Yeah, I saw it was locked. Where's the sceptre at?",1);
sCinema(oBarkley,"dialog","Rutherford:\\It lies in a cave, near the bottom of the island. A fool named Jenkins trapped himself inside a cave and is protecting the sceptre, thus you may encounter difficulties obtaining it.",0);
sCinema(oBarkley,"dialog","Jenkins huh? I've dealt with worse. Thanks for the help, I'm heading out now.",1);
