with (oWall0) solid=0;
oIntro3a.visible=1;
sCinema(oBarkley,"cond",cine_0148);
sCinema(oBarkley,"move","down");
sCinema(oBarkley,"quick","up");
sCinema2(oBarkley,"jump","start");
sCinema2(oBarkley,"move","down",5);
sCinema4(oBarkley,"move","down",8);
sCinema4(oBarkley,"code",cine_0298);
sCinema4(oBarkley,"code",cine_0093);
sCinema4(oBarkley,"code",cine_0299);
sCinema4(oBarkley,"wait",1);
sCinema4(oBarkley,"code",cine_0096);
sCinema4(oBarkley,"wait",0.5);
sCinema(oBarkley,"code",cine_0300);
sCinema(oBarkley,"code",cine_0301);
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"cond",cine_0104);
repeat(9) sCinema(oBarkley,"move","down",5);
sCinema2(oBarkley,"jump","end");
sCinema(oBarkley,"quick","cancel");
sCinema3(oBarkley,"code",cine_0093);
sCinema3(oBarkley,"code",cine_0299);
sCinema3(oBarkley,"wait",3);
sCinema3(oBarkley,"code",cine_0096);
sCinema(oBarkley,"code",cine_0302);
sCinema(oBarkley,"cond",cine_0103);
sCinema(oBarkley,"move","left");
repeat(3) sCinema(oBarkley,"move","down",4);
