oBum0.movement=0;
global.camera=oDummy;
oBum0.t=1;
oBum0.x-=2;
oPunk0.t=1;
oPunk1.t=3;
sCinema(oBum0,"effect","fadeout");
sCinema(oBum0,"code",cine_0153);
sCinema(oBarkley,"sound",mNeoshek);
sCinema(oBum0,"dialog","Where the strong bully the weak for what few neo-shekels they've got.");
sCinema(oBum0,"code",cine_0017);
sCinema(oBum0,"dialog","Ruffian 1:\\Hand over the Neo-Shekels!");
sCinema(oBum0,"dialog","Bum:\\But I need them to buy food..!");
sCinema(oBum0,"code",cine_0153);
sCinema(oBarkley,"sound",mWeari);
sCinema(oBum0,"dialog","Crime is everywhere, weariness and despair behind every corner.");
sCinema(oBum0,"code",cine_0017);
sCinema(oBum0,"dialog","Ruffian 2:\\Gimme 'em!");
sCinema(oPunk1,"move","left",8);
sCinema(oPunk1,"code",cine_0172);
sCinema(oPunk1,"code",cine_0173);
sCinema(oPunk1,"wait",0.3);
sCinema(oPunk1,"code",cine_0174);
sCinema(oBum0,"dialog","Bum:\\OOF!");
sCinema(oPunk1,"wait",0.3);
sCinema(oPunk1,"code",cine_0175);
sCinema(oPunk1,"code",cine_0176);
sCinema(oPunk1,"code",cine_0177);
sCinema1(oPunk1,"move","down");
sCinema1(oPunk1,"move","left");
sCinema(oPunk1,"code",cine_0178);
sCinema(oPunk0,"move","up");
sCinema(oPunk0,"move","right");
sCinema(oPunk0,"move","right");
sCinema(oPunk0,"move","left");
sCinema(oPunk1,"code",cine_0179);
sCinema(oBum0,"dialog","Ruffian 1:\\Ahahaha! C'mon bro, let's get some chups!");
sCinema2(oPunk1,"move","left",5);
sCinema2(oPunk1,"move","left",5);
sCinema2(oPunk1,"move","left",5);
sCinema2(oPunk1,"move","left",5);
sCinema2(oPunk1,"move","left",5);
sCinema2(oPunk1,"move","left",5);
sCinema2(oPunk1,"move","left",5);
sCinema2(oPunk1,"move","left",5);
sCinema2(oPunk1,"move","left",5);
sCinema2(oPunk1,"move","left",5);
sCinema2(oPunk1,"move","left",5);
sCinema(oPunk1,"code",cine_0180);
sCinema(oPunk0,"move","left",5);
sCinema(oPunk0,"move","left",5);
sCinema(oPunk0,"move","left",5);
sCinema(oPunk0,"move","left",5);
sCinema(oPunk0,"move","left",5);
sCinema(oPunk0,"move","left",5);
sCinema(oPunk0,"move","left",5);
sCinema(oPunk0,"move","left",5);
sCinema(oPunk0,"move","left",5);
sCinema(oPunk0,"move","left",5);
sCinema(oPunk0,"move","left",5);
sCinema(oBum0,"dialog","Bum:\\No! My neo-shekels!");
sCinema(oBum0,"effect","fadein");
sCinema(oPunk1,"code",cine_0154);
