sOvar(oAllard,.5);
sBoss("oBBodyguard2");
oBarkley.y-=32;
oHoopz.t=0;
oCyberdwarf.t=0;
oBalthios.t=0;
oBarkley.t=0;
oAllard.visible=0;
oLief.visible=0;
global.nofollow=1;
with (oFollower) x=-999;
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"wait",0.5);
//snd key
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"code",cine_0202);
sCinema(oAllard,"move","right");
sCinema(oAllard,"move","right");
sCinema(oAllard,"move","up");
repeat(4)sCinema(oAllard,"move","right");
sCinema(oAllard,"face","down");
sCinema(oBarkley,"dialog","Allard:\\Hmm? And who exactly are they?");
sCinema(oBarkley,"dialog","Bodyguard:\\They just came in. Didn't say.");
sCinema(oBarkley,"dialog","Allard:\\You there. I don't believe you have an appointment scheduled. If you don't mind, I'd like to ask if you all could leave.");
sCinema(oBarkley,"dialog","Can't do that, doc.",1);
sCinema(oBarkley,"dialog","Allard:\\And why not?");
sCinema(oBarkley,"dialog","You run the gate. We need to get through it.",1);
sCinema(oBarkley,"dialog","Allard:\\There's a procedure for that, you know. Head to the gate, I'm sure the men there will explain it for you.");
sCinema(oBarkley,"dialog","I ain't payin your gatdam toll, Allard.",1);
sCinema(oBarkley,"dialog","Allard:\\Oh really? Well, we'll have to talk about that. First of all though, you know my name but I don't know any of yours.");
sCinema(oBarkley,"dialog","It's none of your fucking business. Just open the gate before your ass gets slammed and jammed.",1);
sCinema(oBarkley,"dialog","Allard:\\Oh wait, I remember you. From all those news reports. Barkley... Charles Barkley, is it?");
sCinema(oBarkley,"dialog","Just let us through the gate.",1);
sCinema(oBarkley,"dialog","Allard:\\Charles Barkley, that's right. You're a wanted man, you know. Sirens have been blaring on the surface all day. We hear the echoes down here. I assume they're looking for you. Fifteen million. That's quite a bit of damage you did to Manhattan, Barkley.");
sCinema(oBarkley,"dialog","That wasn't me you son of a bitch.",1);
sCinema(oBarkley,"dialog","Allard:\\Right. Whenever somebody comes to the sewers, it "+"\"was"+"n't"+" them.\""+" Regardless, you aren't in the best situation now are you? The police and the B-ball Removal Department looking for you topside, and here you are in my office acting like you have some kind of upper hand. Pitiful. You and your friends there are at my mercy, and you come at me with threats. Do you have any idea who I am? I run these sewers. All of these rats bow to me. They need me. I'll give you the chance to turn around now.");
sCinema(oCyberdwarf,"dialog","Barkley, perhaps we shouldn't...",1);
sCinema(oBarkley,"dialog","Shouldn't? He's a fucking tyrant and he needs to be stopped.",1);
sCinema(oBarkley,"dialog","Allard:\\A tyrant? Hahaha. I'm a blessing to these rats. Here's a story for you: I wasn't always a doctor. I worked for a software company. We did computers, vidcons and things. I was grotesque. A pasty, balding wreck. My physical form was flabby and weak... so I decided to change it. Clispaeth put me a disgusting sack of flesh, and so I went to work on it. I studied genetic engineering, plastic surgery, even fashion. I was bald, so I gave myself hair. I cut away my fat and grew muscle in its stead. God gave me a body... I refused it, and made another of my liking. I destroyed God's plan for me, and made another of my own! And to these people in the sewers, I took his place. They come to me, sad souls imprisoned in pathetic husks. I am the one who sets them free! This time, I am their creator! I give them life, and so I claim these sewers as my dominion. And here you make demands of me. In these sewers, I am a god, and I am loved for it! ... You there.");
sCinema(oCyberdwarf,"dialog","Me?",1);
sCinema(oBarkley,"dialog","Allard:\\Your skin. Leathery, patterned, doesn't look synthetic from here. Basketballs, I'm assuming?");
sCinema(oCyberdwarf,"dialog","Y...yes. It is made of basketballs.",1);
sCinema(oBarkley,"dialog","Allard:\\It's patients like you who I can fix. People like you come to me in shackles, and I liberate them. And all I ask from them is obedience, and of course, a modest fee. I am a doctor after all.");
sCinema(oBarkley,"dialog","You're a goddamn lunatic.",1);
sCinema(oBarkley,"dialog","Allard:\\You're a stubborn one aren't you. I gave you a chance. Leonard, take care of them.");
sCinema(oBarkley,"dialog","Bodyguard:\\... Right away, sir.");
sCinema(oBarkley,"code",cine_0201);
sCinema(oBarkley,"code",cine_0006);
