global.b_music=mBattle;
global.nofollow=1;
global.shake=0;
global.plot=5;
with (oFollower) x=-999;
oHellbane.visible=1;
oHellbane.x=144-16;
oHellbane.y=256-48;
oHellbane.t=1;
oBarkley.x=144+16;
oBarkley.y=256-48;
oBarkley.t=3;
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"cond",cine_0148);
sCinema(oBarkley,"dialog","We... We did it... We managed to beat the B-Ball Monster...",1);
sCinema(oHellbane,"dialog","For a minute there, I didn't think we'd make it.",1);
sCinema(oBarkley,"dialog","Are you kidding Balthios? With the way you used those zaubers, it's no wonder they call you the Ultimate Hellbane.",1);
sCinema(oHellbane,"dialog","Heh, I could be better... Hey, what's this?",1);
sCinema(oHellbane,"move","up");
sCinema(oHellbane,"face","right");
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"dialog","It... It looks like a basketball...",1);
sCinema(oBarkley,"move","up");
sCinema(oHellbane,"dialog","This... This looks like my great grandfather's basketball. It wasn't here just a second ago, Barkley. It must be his final farewell to you. He treasured his b-ball more than anything, Charles. You'd better use it wisely.",1);
sCinema(oBarkley,"dialog","I will, Balthios. I will.",1);
sCinema(oBarkley,"item","B-ball",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","He said we should look for a cyberdwarf. What's that?",1);
sCinema(oHellbane,"dialog","More like WHO'S that, Barkley. He's an old friend of my great grandfather's and someone who could help us out greatly. Come on, we'd better get moving or Jordan will catch us.",1);
sCinema(oBarkley,"dialog","Yeah, you're right.",1);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomSewer0;
sA("stopall");
sA("loop",mSpirit);
