if (global.selected=0) {
sBoss("oBDuergar");
sOvar(object_index,1);
oWall0.solid=0;
with (oPlayer) solid=0;
sOvar(object_index,1);
sOvar(oFerry,1);
sParty("del",1); ////////here
sCinema(oBarkley,"dialog","Captain:\\Alright, get on board. We're leaving right now.");
sCinema(oSeaman,"move","down");
sCinema(oSeaman,"move","right");
sCinema(oSeaman,"move","right");
sCinema(oSeaman,"code",cine_0450); //352, 672
sCinema(oBarkley,"move","down");
sCinema(oBarkley,"move","down");
sCinema(oBarkley,"move","right");
sCinema(oBarkley,"move","right");
sCinema(oBarkley,"catchup");
sCinema(oBarkley,"code",cine_0451);
sCinema(oSeaman,"code",cine_0452);
repeat(6) sCinema(oBarkley,"move","right");
sCinema(oSeaman,"code",cine_0453);
sCinema(oSeaman,"code",cine_0454);
repeat (7) sCinema(oSeaman,"move","up");
sCinema(oSeaman,"move","left");
sCinema(oSeaman,"move","left");
sCinema(oSeaman,"move","left");
sCinema(oSeaman,"face","up");
sCinema(oSeaman,"code",cine_0264);
sCinema(oBarkley,"code",cine_0180);
sCinema(oBarkley,"code",cine_0178);
repeat (5) sCinema(oBarkley,"move","up");
repeat (6) sCinema(oBarkley,"move","left");
sCinema1(oSeaman,"code",cine_0265);
repeat (4) sCinema1(oBalthios,"move","up");
repeat (6) sCinema1(oBalthios,"move","left");
sCinema2(oSeaman,"code",cine_0267);
repeat (2) sCinema2(oCyberdwarf,"move","up");
sCinema2(oCyberdwarf,"move","right");
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"cond",cine_0101);
sCinema(oBarkley,"dialog","Captain:\\We be setting sail! Hold onto your pantaloons!");
sCinema(oSeaman,"code",cine_0455);
sCinema(oBarkley,"wait",3);
sCinema(oSeaman,"code",cine_0456);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"tint",c_black,.1);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"tint",c_black,.2);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"tint",c_black,.3);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"tint",c_black,.4);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"dialog","It's... it's beautiful, isn't it?",1);
sCinema(oBalthios,"dialog","You're thinking about Maureen again, aren't you?",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","She loved the water. I'd take her out here sometimes and we'd just look up at the moon. I'd tell her sometimes that the moon looked like a b-ball and she would laugh and tell me I was obsessed. Maybe... maybe I was. It looks like her though, doesn't it?",1);
sCinema(oBalthios,"dialog","The moon?",1);
sCinema(oBarkley,"dialog","Just... the shape. Her head was that shape, that... sphere. Maybe that's why I loved her, because her head was shaped like a b-ball.",1);
sCinema(oBalthios,"dialog","It does resemble her a little.",1);
repeat (6) sCinema(oCyberdwarf,"move","left");
sCinema(oBarkley,"dialog","It's full tonight. You know the moon only gets this way around October 12.",1);
sCinema(oBalthios,"dialog","Oc...October 12? You mean... Columbus Day?",1);
sCinema(oBarkley,"dialog","Yeah, I guess that would make it Columbus Day.",1);
sCinema(oBalthios,"move","right");
sCinema(oBalthios,"dialog","N-no...",1);
sCinema(oBalthios,"move","right");
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"dialog","Balthios?",1);
sCinema(oBalthios,"dialog","I... I must go!",1);
sCinema(oCyberdwarf,"face","right");
repeat (4) sCinema(oBalthios,"move","right",4);
repeat (4) sCinema(oBalthios,"move","down",4);
sCinema(oSeaman,"code",cine_0445);
sCinema(oBarkley,"dialog","Balthios!?",1);
repeat (1) sCinema(oCyberdwarf,"move","up");
sCinema(oCyberdwarf,"dialog","What did you say to him, Charles?",1);
sCinema(oBarkley,"dialog","I don't know, only that-",1);
sCinema(oSeaman,"code",cine_0457);
sCinema(oBarkley,"wait",1);
sCinema(oSeaman,"code",cine_0458);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"jump","start");
sCinema(oCyberdwarf,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oCyberdwarf,"jump","end");
sCinema(oSeaman,"code",cine_0459);
repeat (5) sCinema(oBalthios,"move","up",4);
repeat (4) sCinema(oBalthios,"move","left",4);
sCinema(oBalthios,"dialog","???:\\UOOOOUORR!");
sCinema(oBarkley,"dialog","Wh-what the hell!?",1);
sCinema(oCyberdwarf,"dialog","It's a duergar and it looks like it wants to fight!",1);
sCinema(oBarkley,"dialog","We don't have time for this shit!",1);
sCinema(oCyberdwarf,"dialog","But it looks like we've got no choice! Here it comes!",1);
//sCinema(oBalthios,'dialog',"battle here");
sCinema(oBarkley,"code",cine_0460);
sCinema(oBarkley,"code",cine_0461);
sCinema(oBarkley,"code",cine_0006);
//sCinema(oBarkley,'effect','fadein',3);
//global.roz=RomFerry;
} else if (global.selected=1) {
sCinema(oBarkley,"dialog","Captain:\\Then don't waste my time. I'm only taking people who are serious about the trip.");
}
