global.dialog=1;
sCinema(oBarkley,"dialog","James Ruglia:\\I think I'm gonna vomit...");
sCinema(oBarkley,"dialog","Huh? What's the matter?",1);
sCinema(oBarkley,"dialog","James Ruglia:\\They're matching me up with someone now, I'm so nervous. I don't think I've ever been this nervous before.");
sCinema(oBarkley,"dialog","What's the big deal? It's just a dating service.",1);
sCinema(oBarkley,"dialog","James Ruglia:\\But who knows if the girl they match me up with is the girl I've been dreaming of all my life? Who knows if it's that special girl that will make me happy...");
sCinema(oBarkley,"dialog","K-kinda like Maureen...",1);
sCinema(oBarkley,"dialog","James Ruglia:\\My ideal woman, she'd be like this... \\+She'd have to be caucasian. No other race could make me feel as close-not even Asian.\\+Definately untoned and shorter than me, with long hair. Color is irrelevant because she'd dye it anyway.\\+Someone with good ideals and a moral backbone without being "+"\"old-fashioned\""+". Someone who really likes to huggle and so forth-who could sleep in a single sized bed comfortably with me. Preferably she'd like to wear stuff I pick out for her and she'd be just as willing to do any random little chore or apeasment that I already dedicate so much of my convenience to others for(and her included of course). \\+Big bonus points if she likes my creativity and RPGMaker game(s/coding skill)\\+Someone who could act almost as my double, going anywhere I went, but who needed my help for things. Lifting something, inturpreting more complex Japanese, explaining things clearly, mathematical calculations...\\+My first kid will be a girl named Terra or a boy named Ryukaze. Hopefully this wouldn't need discussion(Though I might think harder about "+"\"Ryukaze\""+"...).\\+I could explain some other 100% necessary no-exception-for-anything details, but those are more "+"\"personal\""+"...\\+One admitable detail for my last point is she'd need to like roleplaying, pretending, make-believe etc. because two things I like in private are flattery (and flattering) and "+"\"foreplay\""+".");
sCinema(oBarkley,"dialog","J... just like Maureen...",1);
