global.dialog=1;
sBoss("oBCreelman");
oJordan.x=-999;
sOvar(oIntro20,1);
repeat (14) sCinema1(oHoopz,"move","up");
repeat (14) sCinema2(oBalthios,"move","up");
repeat (14) sCinema3(oCyberdwarf,"move","up");
sCinema3(oCyberdwarf,"move","left");
sCinema3(oCyberdwarf,"face","up");
sCinema(oBarkley,"code",cine_0239);
repeat (15) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","???:\\Tell me, Charles Barkley, what is a b-ball?");
sCinema(oBarkley,"dialog","Wh-what? Who are you?",1);
sCinema(oBarkley,"dialog","???:\\Just humor me, tell me what a b-ball is.");
sCinema(oBarkley,"dialog","It's... it's an orange ball with black lines on it. It bounces well but it's easy to hold and throw, perfect for slams and shots.",1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","???:\\That was good, Charles. Tell me more about the lines on a b-ball. The black lines.");
sCinema(oFollower0,"dialog","Charles...",1);
sCinema(oBarkley,"dialog","What about the lines? They're black. They divide the ball into little segments and they improve grip.",1);
sCinema(oBarkley,"dialog","???:\\Ahhh, the segments. Did you know those lines are the reason I got in this business?");
sCinema(oBarkley,"dialog","What do you mean? What are you talking about...",1);
sCinema(oBarkley,"dialog","???:\\It's true. You see, those lines, they mean different things to you than they do to me. You mentioned that the lines divide the ball into segments. I believe you are wrong, Charles Barkley. I believe that the lines are in fact a symbol of unity, that they are the only things holding the ball together. Have you ever considered that even though the lines all go in different directions, they all have the exact same point of origin and end? Have you ever considered that without those lines, you'd be staring at a bunch of strips of leather and rubber and not a basketball? They bring the ball together. That is why I made basketballs, Charles Barkley. To bring people together, to show them that the lines on a b-ball do not divide it, but hold it together. I suppose I failed.");
sCinema(oFollower2,"dialog","Scott H. Creelman...",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oCEO,"face","down");
sCinema(oBarkley,"dialog","Scott H. Creelman:\\Yes, that was my name before the Purge, back when I was CEO of a company called Spalding, back when we had a dream... Heh, the only dreams I have now are nightmares.");
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","We came for the prototype, Creelman. We need it to stop B.L.O.O.D.M.O.S.E.S.",1);
sCinema(oBarkley,"dialog","Scott H. Creelman:\\I know. I've been waiting for you.");
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Can I have it?",1);
sCinema(oBarkley,"dialog","Scott H. Creelman:\\Hah!\\Haha ha!\\HAHA HAHAHAHAHAHA!");
sCinema(oBarkley,"dialog","Scott H. Creelman:\\I've been waiting for you to ask me that, Charles Barkley! I've been waiting 12 years for this! Come Charles Barkley, face my danger!");
sCinema(oBarkley,"dialog","No, Creelman. I won't fight you. You're not my enemy.",1);
sCinema(oBarkley,"dialog","Scott H. Creelman:\\Hahaha, you don't get it, do you Charles Barkley? All of this, it's ~FATE~. The Purge, the prototype, our meeting. All of this is ~FATE~. You have no choice as to whether we will battle or not. It was already predestined.");
sCinema(oBarkley,"dialog","So be it, Creelman. We'll see what ~FATE~ has in store!",1);
sCinema(oBarkley,"code",cine_0040);
sCinema(oBarkley,"code",cine_0240);
sCinema(oBarkley,"code",cine_0006);
sA("stopall");sA("loop",mParade);
