sOvar(object_index,3);
sPos("load");
global.nofollow=1;
with (oFollower) x=-999;
sCinema(oBarkley,"wait",1);
sCinema(oShadowBarkley,"dialog","Kwa... Kwahuaha... KWAHUAHAHAHA!",1);
sCinema(oBarkley,"dialog","What's so funny, chump?",1);
sCinema(oShadowBarkley,"dialog","You've accomplished nothing. Nothing! The Ultimate B-Ball will destroy Earth whether I'm here or not. The Second B-Ball Purge will destroy all mankind!",1);
sCinema(oBalthios,"dialog","C... Clispaeth...",1);
sCinema(oHoopz,"dialog","D... dad... what are we gonna do?",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"code",cine_0341);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"code",cine_0342);
sCinema(oBarkley,"dialog","Balthios, Cyberdwarf, take Hoopz to the escape pods.",1);
sCinema(oBalthios,"dialog","Charles, are you... sure about this?",1);
sCinema(oHoopz,"dialog","Dad?",1);
sCinema(oBarkley,"dialog","Yes, I am sure.",1);
sCinema(oCyberdwarf,"dialog","Barkley...",1);
sCinema(oBarkley,"dialog","Just do it, damnit! Get him somewhere safe!",1);
sCinema(oCyberdwarf,"dialog","Yes, Charles.",1);
sCinema(oHoopz,"dialog","D-dad!?",1);
sCinema(oCyberdwarf,"dialog","Come on, Hoopz. We've got to go.",1);
sCinema(oHoopz,"dialog","DAD!",1);
sCinema(oBalthios,"dialog","Come Hoopz, we must move quickly.",1);

sCinema(oBarkley,"code",cine_0180);
sCinema(oBarkley,"code",cine_0178);
sCinema(oBarkley,"code",cine_0295);
repeat (6) sCinema1(oBalthios,"move","down",4);
repeat (6) sCinema2(oCyberdwarf,"move","down",4);
repeat (6) sCinema3(oHoopz,"move","down",4);
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"cond",cine_0101);
sCinema(oBarkley,"cond",cine_0103);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomNecronCourt;
sA("stopall");
