global.nofollow=0;
sParty("add",1);sParty("add",3);sParty("add",4);
sOvar(object_index,2);
sPos("load");
oFollower.x=oBarkley.x;
oFollower.y=oBarkley.y;
oJordan.t=2;
oBarkley.t=0;
sCinema(oBarkley,"wait",2);
sCinema(oJordan,"move","up");
sCinema(oBarkley,"wait",1.2);
sCinema(oJordan,"move","up");
sCinema(oBarkley,"wait",1.2);
sCinema(oJordan,"dialog","S... So desu ne...",1);
sCinema(oFollower0,"dialog","So be it...",1);
sCinema(oBarkley,"dialog","If you can't slam with the best, then jam with the rest.",1);
sCinema(oBarkley,"wait",1.2);
sCinema(oJordan,"code",cine_0335);
sCinema(oBarkley,"code",cine_0277);
sCinema(oBarkley,"wait",2);
sCinema(oFollower3,"dialog","Mr. Jordan is gone, isn't he dad?",1);
sCinema(oBarkley,"dialog","He's gone for good, Hoopz. He won't be coming back this time.",1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","There's... there's nothing more to be said. Come on, let's go.",1);
sCinema(oFollower0,"dialog","Right.",1);
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0336);
sCinema(oBarkley,"tint",c_black,0);
sA("stopall");
sA("loop",mJordan);
