sParty("del",1);sParty("del",3);sParty("del",4);
sBoss("Jordan");
sOvar(object_index,1);
sCinema(oBarkley,"wait",3);
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"dialog","What the, I haven't seen one of these since... Since the purge.",1);
sCinema(oFollower0,"dialog","This B-Ball court confirms our suspicions. B.L.O.O.D.M.O.S.E.S. has to be here.",1);
sCinema(oFollower2,"dialog","My dwarf senses do not react well to this derelect arena... We had better brace ourselves, or risk being ambushed.",1);
sCinema(oBarkley,"code",cine_0074);
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"move","up");
repeat (4) sCinema(oBarkley,"move","left");
repeat (5) sCinema(oBarkley,"move","up");
repeat (4) sCinema(oBarkley,"move","right");
repeat (3) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"code",cine_0337);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Huh!? Who did that?",1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","???|Jordan:\\What a surprise, to find you here in the B.L.O.O.D.M.O.S.E.S. headquarters, Barkley.");
sCinema(oBarkley,"dialog","That voice... Jordan! Jordan, you son of a bitch! You sick goddamn son of a bitch!",1);
repeat (4) sCinema(oJordan,"move","down");
sCinema(oBarkley,"code",cine_0338);
sCinema(oBarkley,"wait",1);
sCinema(oJordan,"dialog","You never did know when to quit... I'm afraid this is as far as you're going to get.",1);
sCinema(oBarkley,"dialog","You know damn well that Chaos Dunk in Manhattan wasn't me! Don't be a gatdam fool!",1);
sCinema(oJordan,"dialog","You know, Charles, I thought you were smarter than that. I thought you realized this wasn't even about the Chaos Dunk anymore.",1);
sCinema(oBarkley,"dialog","What are you on about?",1);
sCinema(oJordan,"dialog","Don't you hear it? The cheering of the fans, the dribbling of pre-game warmup b-balls, the swishing of nets as ballers perfect their shots, and...",1);
sCinema(oBarkley,"wait",1);
sCinema(oJordan,"dialog","Sweet Georgia Brown.",1);
sCinema(oBarkley,"dialog","Sweet Georgia Brown...?",1);
sCinema(oJordan,"dialog","It's been ages since I last heard that song but... but I can hear it now, a symphony of whistles and toots.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oJordan,"move","down");
sCinema(oJordan,"dialog","This meeting between you and I is the culmination of thousands of years of b-ball. This is b-ball in all its glory, this is the final game! It's just you and me, Barkley. No refs. No whistles. No rules. Just you, me, and Sweet Georgia Brown.",1);
sCinema(oBarkley,"wait",1);
sCinema(oFollower0,"dialog","Barkley, you don't need to do this. You don't need to fight Jordan.",1);
sCinema(oBarkley,"face","down");
sCinema(oBarkley,"dialog","This is something I gotta do Balthios...",1);
sCinema(oBarkley,"code",cine_0339);
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"dialog","Bring it Jordan. Come on and slam and welcome to the jam. Come on and slam if you want to jam!",1);
sCinema(oBarkley,"code",cine_0040);
sCinema(oBarkley,"code",cine_0340);
sCinema(oBarkley,"code",cine_0006);
