sound_loop(mSiren);
xx=320;
cou=0;
dir=0;
gtt="!NEO NEW YORK CHAOS DUNK ADVISORY WARNING! A MEASURED 19.7 MEGAJOULE OF NEGATIVE BBALL PROTONS HAVE BEEN DETECTED. A CHAOS DUNK IS IMMINENT. FIND UNDERGROUND SHELTER IMMEDIATELY. THIS IS NOT A TEST.";
