if (room!=RomSubwayCar0) { oTubman.t=1; exit; }
oHoopzdummy.visible=1;
oHoopzdummy.y-=8;
oHoopzdummy.x-=2;
oCyberdwarf.x=oCyberdwarf.xstart-4;
oBalthios.x=oCyberdwarf.x+32;
oBalthios.y=oCyberdwarf.y;
oBalthios.t=2;
oCyberdwarf.t=2;
oBarkley.t=2;
oBarkley.x-=12;
global.nofollow=1;
global.skipper=12;
with (oFollower) x=-999;
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","Harriet Tubman:\\What's his name?");
sCinema(oBarkley,"dialog","What?",1);
sCinema(oBarkley,"dialog","Harriet Tubman:\\Your son, what's his name?");
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","It's Hoopz.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","Harriet Tubman:\\He reminds me of someone I used to know. Someone from a long time ago. His name was... Judas.");
sCinema(oCyberdwarf,"dialog","(J-Judas?)",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","Harriet Tubman:\\He was... the only man I ever loved. Or maybe the only man I ever tried to love. After he was gone, I just couldn't handle any other men. They say only the people who find true love can never move on. Maybe that's what we had.");
sCinema(oBarkley,"dialog","What happened? Do you mind if I ask?",1);
sCinema(oBarkley,"dialog","Harriet Tubman:\\It was a long time ago, I can hardly remember it. He got caught up in some stupid fight and got killed. I told him it was stupid, he... he knew it was stupid but he was one of those guys who held on to an idea and wouldn't let go.");
sCinema(oBarkley,"dialog","My wife Maureen died twelve years ago. I could never bring myself to love another woman after I lost her, either.",1);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","How long have you been down here?",1);
sCinema(oBarkley,"dialog","Harriet Tubman:\\In Proto Neo New York?");
sCinema(oBarkley,"dialog","In the Underground Railroad.",1);
sCinema(oBarkley,"dialog","Harriet Tubman:\\Heh, it seems like forever. Maybe it has been, I don't know. Every day seems like forever without...");
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","Harriet Tubman:\\...but today didn't seem so bad.");
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","Harriet Tubman:\\We're almost there. Most people don't come to the outskirts of Neo New York unless they're running from something... or maybe I'm wrong?");
sCinema(oBarkley,"dialog","I don't know if you're wrong or you're right, really.",1);
sCinema(oBarkley,"dialog","Harriet Tubman:\\It... it's not my business.");
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomOutskirts;
