draw_text(x+gx,y+sp+pp,string_hash_to_newline(sAlBhed(global.char_name[i],1)));
draw_text(x+gx,y+sp+pp+10,string_hash_to_newline("Arm")); 
draw_text(x+gx,y+sp+pp+20,string_hash_to_newline("Body")); 
draw_text(x+gx,y+sp+pp+30,string_hash_to_newline("Bling"));
draw_set_color(make_color_rgb(200,200,200));
draw_text(x+gx+28,y+sp+pp+10,string_hash_to_newline(global.char_eweapon[i]));
draw_text(x+gx+28,y+sp+pp+20,string_hash_to_newline(global.char_earmour[i]));
draw_text(x+gx+28,y+sp+pp+30,string_hash_to_newline(global.char_eaccess[i]));
draw_set_color(c_white);
if (global.char_res2[i]!="") {
draw_set_color(c_fuchsia);
draw_text(x+gx+134,y+sp+pp,string_hash_to_newline(global.char_res2[i]));
draw_set_color(c_white);
} else draw_text(x+gx+134,y+sp+pp,string_hash_to_newline("Healthy"));
draw_text(x+gx+134,y+sp+pp+10,string_hash_to_newline("VP "));
draw_text(x+gx+134,y+sp+pp+20,string_hash_to_newline("BP "));
draw_set_color(make_color_rgb(255,128,128)); draw_text(x+gx+134+18,y+sp+pp+10,string_hash_to_newline(string(global.char_chp[i])+"/"+string(global.char_rhp[i])));
draw_set_color(make_color_rgb(128,128,255)); draw_text(x+gx+134+18,y+sp+pp+20,string_hash_to_newline(string(global.char_czp[i])+"/"+string(global.char_rzp[i])));
draw_set_color(c_white);
draw_text(x+gx+134,y+sp+pp+30,string_hash_to_newline("Speed ")); 
draw_text(x+gx+134+73,y+sp+pp+30,string_hash_to_newline("Power ")); 
draw_text(x+gx+134+73,y+sp+pp+10,string_hash_to_newline("Guard ")); 
draw_text(x+gx+134+73,y+sp+pp+20,string_hash_to_newline("Brain ")); 
draw_set_color(make_color_rgb(128,255,128));
draw_text(x+gx+134+34,y+sp+pp+30,string_hash_to_newline(string(floor(global.char_rfootwork[i]))));
draw_text(x+gx+134+73+32,y+sp+pp+30,string_hash_to_newline(string(global.char_rattack[i])));
draw_text(x+gx+134+73+32,y+sp+pp+10,string_hash_to_newline(string(global.char_rdefense[i])));
draw_text(x+gx+134+73+32,y+sp+pp+20,string_hash_to_newline(string(global.char_rzauberacity[i])));
draw_set_color(c_white);
