global.dialog=1;
itemf[0]="Mystic B-ball";
itemf[1]="Egyptian Gun";
itemf[2]="Dwarfstear";
itemf[3]="Dwarf Muscle";
itemf[4]="Hell Zauber";
itemf[5]="Referee Uniform";
itemf[6]="Mithril Sweatband";
itemf[7]="Facemask";
itemf[8]="Zaubermancer Garb";
itemf[9]="Tek-Skeleton";
itemf[10]="Pumps";
itemf[11]="Cyber-Gauntlet";
itemf[12]="";
sCinema(oBarkley,"dialog","Bert:\\Not many people come here, you on the run?");
sCinema(oBarkley,"dialog","We're looking for Cuchulainn's Tomb. You know where it is?",1);
sCinema(oBarkley,"dialog","Bert:\\It's in the building at the back of the parking lot. You're not thinking of going in unprepared, are you? You'd better stock up, man.");
sCinema(oBarkley,"code",cine_0002);
sCinema(oBarkley,"cond",cine_0003);
sCinema(oBarkley,"dialog","Bert:\\Thanks a lot man. You take care of yourself in Cuchulainn's Tomb. Most people who go in don't come back out.");
