sOvar(object_index,2);
sOvar(oMack,3);
sPos("load");
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"dialog","Reginald:\\You... Ughhh... You don't understand, none of you...");
sCinema(oDiabeastfake,"move","down");
sCinema(oBarkley,"dialog","Reginald:\\Aghh... You will regret this. You will -- orgrhh -- go down in the history books as the man who plagued humanity with diabetes...");
sCinema(oDiabeastfake,"move","down");
sCinema(oDiabeastfake,"wait",1);
repeat (4) sCinema(oDiabeastfake,"move","down",6);
sCinema(oBarkley,"code",cine_0128);
sCinema(oBarkley,"dialog","Reginald:\\Ahhhhhhh!!!");
sCinema(oDiabeastfake,"wait",1);
repeat (4) sCinema(oBarkley,"move","down");
sCinema(oBarkley,"item","Immaculate Rod",1);
sCinema(oBarkley,"dialog","We got the rod, now let's get the hell out of here.",1);
sCinema(oBarkley,"code",cine_0074);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomLibertyMain;
