oSoldier0.t=1;
oSoldier1.t=1;
oSoldier1.solid=0;
oSoldier1.dap=0;
oSoldier1.depth=0;
oSoldier2.t=3;
oSoldier3.t=3;
with (oPump) instance_destroy();
with (oBum0) instance_destroy();
sCinema(oBarkley,"code",cine_0313);
sCinema(oBarkley,"code",cine_0314);
sCinema(oBarkley,"cond",cine_0148);
repeat(4) sCinema(oBarkley,"move","down");
sCinema(oBarkley,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"wait",0.5);
sCinema(oSoldier3,"move","left",5);
sCinema(oBarkley,"quick","up");
sCinema1(oSoldier3,"hurt",oRaygun,oBarkley,(16*1)+8);
sCinema1(oBarkley,"wait",0.5);
sCinema1(oBarkley,"move","up");
sCinema2(oBarkley,"move","up");
sCinema2(oSoldier3,"hurt",oRaygun,oSoldier1,(16*4)+8);
sCinema2(oSoldier3,"code",cine_0281);
sCinema2(oBarkley,"wait",0.5);
sCinema(oBarkley,"code",cine_0269);
sCinema(oBarkley,"code",cine_0270);
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"cond",cine_0101);
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"wait",0.5);
sCinema(oSoldier2,"move","left",5);
sCinema(oBarkley,"quick","down");
sCinema3(oSoldier3,"hurt",oRaygun,oBarkley,(16*1)+8);
sCinema3(oBarkley,"wait",0.5);
sCinema3(oBarkley,"move","down");
sCinema4(oBarkley,"move","down");
sCinema4(oSoldier3,"hurt",oRaygun,oSoldier0,(16*4)+8);
sCinema4(oSoldier3,"code",cine_0315);
sCinema4(oBarkley,"wait",0.5);
sCinema(oBarkley,"code",cine_0271);
sCinema(oBarkley,"code",cine_0158);
sCinema(oBarkley,"cond",cine_0103);
sCinema(oBarkley,"cond",cine_0104);
sCinema(oBarkley,"move","down");
repeat(20) sCinema(oBarkley,"move","left",5);
repeat(3) sCinema(oBarkley,"move","down",4);
