sPos("load");
sOvar(oSign1,1.6);
with (oFollower) x=oBarkley.x;
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"code",cine_0203);
sCinema(oBarkley,"code",cine_0204);
sCinema(oBarkley,"cond",cine_0205);
sCinema(oBarkley,"move","left");
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"code",cine_0206);
sCinema(oBarkley,"code",cine_0204);
sCinema(oBarkley,"cond",cine_0205);
sCinema(oBarkley,"move","left");
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"code",cine_0206);
sCinema(oBarkley,"code",cine_0204);
sCinema(oBarkley,"cond",cine_0205);
sCinema(oBarkley,"code",cine_0207);
sCinema(oBarkley,"cond",cine_0208);
sCinema(oBarkley,"tint",c_white,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0209);
sCinema(oBarkley,"tint",c_white,0);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0210);
sCinema(oBarkley,"wait",3);
sCinema(oBarkley,"dialog","The... fog.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","Ghost Dad, I... may never know who you were in life, but may you find the peace you sought in death...",1);
sCinema(oBarkley,"move","left");
sCinema(oBarkley,"move","left");
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",.6);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomProtoJuwanna;
