oBarkley.x=160-4;
oBarkley.y=320;
oBarkley.visible=0;
global.camera=oHoopz
sCinema(oBarkley,"cond",cine_0148);
sCinema(oBarkley,"code",cine_0017);
sCinema(oHoopz,"dialog","He said he'd be back soon, I'm going in there!",1);
sCinema(oCyberdwarf,"dialog","Hoopz, no! It's too dangerous!",1);
sCinema(oHoopz,"dialog","B-but dad!",1);
sCinema(oCyberdwarf,"dialog","Hoopz...",1);
sCinema(oBarkley,"dialog","???:\\I'm here, Hoopz.");
sCinema(oHoopz,"face","up");
sCinema(oCyberdwarf,"face","up");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"code",cine_0264);
repeat (3) sCinema(oBarkley,"move","down");
sCinema(oBarkley,"wait",1);
sCinema(oHoopz,"dialog","Dad! Are you okay!? What happened?",1);
sCinema(oBalthios,"dialog","Barkley, what happened?!",1);
sCinema(oBarkley,"dialog","I... I felt this b-ball calling me from deep inside Cuchulainn's Tomb. It was a powerful voice and it told me that I could save b-ball if I defeated B.L.O.O.D.M.O.S.E.S. It... it lent me its powers and the ability to Double Dribble.",1);
sCinema(oBalthios,"dialog","Double Dribble, you mean... dual wield two b-balls?",1);
sCinema(oCyberdwarf,"dialog","My lord...",1);
sCinema(oBarkley,"dialog","I control the powers of Shimmerglobe, B-Ball of the Ancient Proto-Dwarfs and the Hell B-Ball, forged on the anvil of jamicite. I now have the power to shoot a three-pointer from 30 yards away.",1);
sCinema(oBalthios,"dialog","Barkley, that's not a three-pointer. That's a four-pointer.",1);
sCinema(oHoopz,"dialog","Well now that we've got the power to counter the Ultimate B-Ball and B.L.O.O.D.M.O.S.E.S., what do we do now?",1);
sCinema(oCyberdwarf,"dialog","I... I don't know.",1);
sCinema(oBalthios,"dialog","We just don't know where B.L.O.O.D.M.O.S.E.S. is. It almost seems like all of this was for nothing.",1);
sCinema(oCyberdwarf,"dialog","It could take me days or weeks or months to divine the location of B.L.O.O.D.M.O.S.E.S. but by then it may be too late. My scrying powers can only go so far.",1);
sCinema(oHoopz,"dialog","But... we can't just give up you guys! We can't just stop everything!",1);
sCinema(oBalthios,"dialog","No, we can't...",1);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","Necron 5.",1);
sCinema(oCyberdwarf,"dialog","What?",1);
sCinema(oBarkley,"dialog","Necron 5. The Ultimate B-Ball is on Necron 5.",1);
sCinema(oBalthios,"dialog","Barkley, how do you know this?",1);
sCinema(oBarkley,"dialog","I don't know... I just... do. I can feel it. I can feel its energy coming from Necron 5.",1);
sCinema(oCyberdwarf,"dialog","Are you channeling its power through the Hell B-Ball?",1);
sCinema(oBarkley,"dialog","I don't know, I think so. All I know is that it's on Necron 5.",1);
sCinema(oHoopz,"dialog","What's Necron 5, Mr. James?",1);
sCinema(oBalthios,"dialog","The Necron 5 is an intergalactic slave ship, Hoopz. Those that spoke out against the government during the Purge who weren't executed were put on Necron 5 to do hard labor in the tupperware mines. But even if we know it's on the Necron 5, it's still in outer space. How are we going to get there?",1);
sCinema(oCyberdwarf,"dialog","My ship... the one I crashed landed in when I came to this planet. It's south of Neo New York. We can use that.",1);
sCinema(oBarkley,"dialog","I thought your ship was destroyed when you came to Earth. That's what you said back in Cesspool X.",1);
sCinema(oCyberdwarf,"dialog","It was, but I've been here a long time, Barkley. Long enough to repair my ship. I've wanted to leave this planet for a long time but I've been searching for the b-ball messiah.",1);
sCinema(oBarkley,"dialog","Well how do we get to your ship?",1);
sCinema(oCyberdwarf,"dialog","We'll have to leave Neo New York and go south. It's not far away and it's not hard to find.",1);
sCinema(oBarkley,"dialog","Alright. Then we'll leave for your ship and head to the Necron 5.",1);
sCinema(oHoopz,"dialog","Is everything gonna be alright, dad?",1);
sCinema(oBarkley,"dialog","I hope so Hoopz. I sure hope so.",1);
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0303);
sCinema(oBarkley,"tint",c_black,0);
