global.dialog=1;
with (oFollower) x=-999;
sOvar(object_index,1);
sPos("load");
sCinema(oBarkley,"code",cine_0241);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0095);
sCinema(oDGarnett,"move","down");
sCinema(oDGarnett,"dialog","B-Barkley...",1);
sCinema(oBarkley,"move","down");
sCinema(oBarkley,"dialog","Kevin...",1);
sCinema(oDGarnett,"dialog","I'm... I'm sorry.",1);
sCinema(oBarkley,"dialog","Kevin?",1);
sCinema(oDGarnett,"dialog","All these years... I blamed you for what happened, I blamed you for the Purge and b-ball being taken away. I trained in a dojo for 12 years to get strong enough to defeat you and when I finally get the chance... in one moment... one little moment, I see that everything I've believed, everything I've driven myself towards is wrong. I tried to force myself to believe that if I killed you, everything would be better. I tried to tell myself that if I fueled my actions with hate rather than understanding and acceptance that I could make things the way they were. Heh! All those years slaving away in a dojo and I didn't think of helping the people around me. No. I was a fool... I'm... I'm sorry.",1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Wow, say it don't spray it.",1);
sCinema(oDGarnett,"dialog","Goodbye... I hope someday... you can forgive me...",1);
sCinema(oBarkley,"tint",c_white,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0242);
sCinema(oBarkley,"tint",c_white,0);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Goodbye, Kevin...",1);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomDimensionArena0;
