oBarkley.x=-99;
with (oFollower) x=-99;
sOvar(object_index,1);
sCinema(oBarkley,"cond",cine_0148);
sCinema(oFollower3,"dialog","Whoa! This is just like in my vidcons!",1);
sCinema(oFollower2,"dialog","So this is the BBall Dimension portal...",1);
sCinema(oBarkley,"dialog","I feel... Different. It feels like I'm going home.",1);
sCinema(oBarkley,"wait",.9);
sCinema(oBarkley,"dialog","...\\...\\awesome...\\baby...");
sCinema(oBarkley,"dialog","Did you hear that?",1);
sCinema(oFollower0,"dialog","Yes, the BBall Portals retain resonance of those passing through it because of the immense amount of bballjoules it takes to shift planes.",1);
sCinema(oBarkley,"dialog","That voice sounded familiar...",1);
sCinema(oBarkley,"wait",.9);
sCinema(oBarkley,"dialog","... ...dipsy-doo dunkeroo slam-jam-bam, baby!");
sCinema(oBarkley,"dialog","That's Dick Vitale! He must have made it to the BBall Dimension, too.",1);
sCinema(oFollower2,"dialog","Look's like we're almost there, get ready to brace for the dimensional shift!",1);
sCinema(oBarkley,"code",cine_0262);
sCinema(oBarkley,"wait",2.5);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomDimensionMain;
