if (sOvar(object_index,-1)=1) exit;
global.dialog=1;
oBarkley.move="";
oDavis.t=0;
oCosby.t=0;
oCagedBalla.alarm[7]=-1;
sOvar(object_index,1);
sPos("save");
sCinema(oBarkley,"move","right");
sCinema(oFollower3,"dialog","I'm feeling strange again dad.",1);
sCinema(oBarkley,"code",cine_0106);
sCinema(oBarkley,"dialog","I... I am too, son. Just stay close. We're gonna be out of here as quick as we can.",1);
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"code",cine_0009); 
sCinema(oBarkley,"code",cine_0107);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"tint",c_black,0);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Doctor Davis:\\Increase jam capacity to 300%. Standby.");
repeat (3) sCinema(oDavis,"move","down");
repeat (4) sCinema(oDavis,"move","left");
sCinema(oDavis,"face","up");
sCinema(oBarkley,"wait",1);
sCinema(oCagedBalla,"face","right");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"face","up");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"face","down");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"face","left");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"jump","start");
sCinema(oCagedBalla,"jump","end");
sCinema(oCagedBalla,"face","right");
sCinema(oCagedBalla,"jump","start");
sCinema(oCagedBalla,"jump","end");
sCinema(oCagedBalla,"face","left");
sCinema(oCagedBalla,"jump","start");
sCinema(oCagedBalla,"jump","end");
sCinema(oCagedBalla,"face","right");
sCinema(oCagedBalla,"jump","start");
sCinema(oCagedBalla,"jump","end");
sCinema(oCagedBalla,"face","left");
sCinema(oCagedBalla,"jump","start");
sCinema(oCagedBalla,"jump","end");
sCinema(oCagedBalla,"face","right");
sCinema(oCagedBalla,"jump","start");
sCinema(oCagedBalla,"jump","end");
sCinema(oBarkley,"dialog","Doctor Davis:\\It is amazing, isn't it Cosby?");
sCinema(oBarkley,"dialog","Doctor Cosby:\\Yes, Davis. It is indeed amazing but... but I can't help but feel that something about it is wrong.");
sCinema(oBarkley,"dialog","Doctor Davis:\\Worried again? How many times do I have to tell you, Cosby? Nothing will go wro-");
sCinema(oCagedBalla,"jump","start");
sCinema(oCagedBalla,"move","right");
sCinema(oCagedBalla,"move","right");
sCinema(oCagedBalla,"jump","end");
sCinema(oBarkley,"code",cine_0018);
repeat (10) {
sCinema(oBarkley,"code",cine_0108);
sCinema(oBarkley,"wait",0.1);
}
sCinema(oBarkley,"code",cine_0109);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"tint",c_white,1);
sCinema(oBarkley,"code",cine_0110);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"tint",c_gray,0);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Doctor Davis:\\Holy shit! What the hell was that!?");
sCinema(oBarkley,"dialog","Doctor Cosby:\\Clispaeth Christ! The test subject... he just performed a Chaos Dunk!");
sCinema(oBarkley,"dialog","Doctor Davis:\\Dear lord... What have we done, Cosby? What have we done?! Somebody call a doctor! Emergency, code red, call a doctor!");
sCinema(oCosby,"move","down");
sCinema(oBarkley,"dialog","Doctor Cosby:\\It's... it's too late for that...He's gone, Davis.");
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"code",cine_0111); 
sCinema(oBarkley,"code",cine_0112);
sCinema(oBarkley,"code",cine_0113);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"tint",c_black,0);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"dialog","Something happened here. I can't quite put my finger on it.",1);
sCinema(oFollower0,"dialog","I do too, Barkley. Something terrible.",1);
repeat (3) sCinema(oBarkley,"move","right");
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"face","down");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"face","down");
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","It's probably just superstition, we should move on.",1);
sCinema(oBarkley,"code",cine_0014);
