//160,176
//global.skipper=7;
oBaller.visible=1;
oBaller.face=14;
if (global.victorian=0) oBaller.name="Dikembe Mutombo";
else oBaller.name="Dikembe Mutombo";
oVince.t=0;
oHoopz.t=0;
oCyberdwarf.t=0;
oBalthios.t=0;
oBarkley.t=0;
oBarkley.y-=16;
if (global.plot>8) { exc=oVince; inc=oHoopz; }
else { exc=oHoopz; inc=oVince; }
global.nofollow=1;
with (oFollower) x=-999;
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"cond",cine_0148);
if (sOvar(object_index,-1)=-1) {
global.b_music=mEpicbattle;
ene[0]="oBDiekembe,21,48,96";ene[1]="";
exc.x=-999;
sOvar(object_index,1);
repeat (2) sCinema1(oBalthios,"move","up");
repeat (2) sCinema2(oCyberdwarf,"move","up");
repeat (1) sCinema3(inc,"move","up");
sCinema(oBarkley,"code",cine_0181);
repeat (2) sCinema(oBarkley,"move","up");
sCinema(oBalthios,"dialog","A-amazing... Dikembe Mutombo's tomb is even more fantastic than I had first expected. Look at this, a reflective pool, two statues of Teresa, patron saint of slams and jams...",1);
sCinema(oCyberdwarf,"dialog","They say Dikembe Mutombo was a deeply religious baller.",1);
sCinema(oBarkley,"dialog","Yeah. Yeah he was. Before every game, he'd say a prayer to whatever gods of b-ball he believed in to improve his game. I don't know if he was humble or crazy, because he attributed his abilities to Clispaeth. He had no idea the measure of his own talent.",1);
sCinema(oBarkley,"wait",1);
if (global.plot>8) {
sCinema(oHoopz,"dialog","Dikembe...",1);
sCinema(oBarkley,"dialog","Yes Hoopz, Dikembe. You've met him. Heh, he was even at the hospital when you were born. You were definitely too young to remember though.",1);
sCinema(oHoopz,"dialog","I don't know dad. Something about this place... it seems familiar. Maybe I do remember him after all.",1);
} else {
sCinema(oBarkley,"code",cine_0182);
sCinema(oBarkley,"wait",1);
sCinema(oVince,"dialog","D... Dikembe...",1);
sCinema(oBarkley,"dialog","Vince, you remember something?",1);
sCinema(oVince,"dialog","I... don't know...",1);
}
sCinema(oCyberdwarf,"dialog","Well Barkley, we're here. Pay your respects and we can move on.",1);
sCinema(oBarkley,"dialog","I... I just wanted to say, Dikembe, that I... I always envied your talent and abilities and sometimes... sometimes I wished I was you. I just wanted to say... I'm sorry.",1);
sCinema(oBarkley,"code",cine_0183);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Huh? What's going on?",1);
sCinema(oBaller,"move","down",8);
sCinema(oBaller,"move","down",8);
repeat(22) sCinema(oBaller,"move","right",8);
sCinema(oBaller,"move","down",8);
sCinema(oBaller,"move","down",8);
sCinema(oBarkley,"dialog","BOOOOOOOOM!");
repeat(24) sCinema(oBaller,"move","left",8);
sCinema(oBaller,"move","down",8);
sCinema(oBaller,"move","down",8);
sCinema(oBarkley,"dialog","SHAKA!");
repeat(24) sCinema(oBaller,"move","right",8);
sCinema(oBaller,"move","down",8);
sCinema(oBaller,"move","down",8);
sCinema(oBaller,"dialog","LAKA!");
repeat(12) sCinema(oBaller,"move","left",8);
sCinema(oBaller,"face","down");
sCinema(oBalthios,"dialog","Look out! It's the ghost of Dikembe Mutombo!",1);
sCinema(oBarkley,"code",cine_0184);
sCinema(oBarkley,"code",cine_0185);
sCinema(oBarkley,"code",cine_0006);
//sCinema(oBarkley,'effect','fadein',3);
//global.roz=RomSewerTomb0;
} else {
sA("stopall");
sA("loop",mSpirit);
global.b_music=mBattle;
//battle
exc.x=-999;
oBaller.x=160+16-4;
oBaller.t=2;
oBaller.y=128;
oBarkley.y-=32;
inc.y-=16;
oHoopz.y-=16;
oBalthios.y-=32;
oCyberdwarf.y-=32;
sCinema(oBarkley,"item","Femur",1);
sCinema(oBarkley,"dialog","D-Dikembe, is it... is it really you?",1);
sCinema(oBaller,"dialog","Yes Barkley, it is really me. You have freed me from the ancient and deadly b-ball curse that caused me to eternally haunt these halls in limbo, trapped between this life and the B-Ball Dimension. I feel my ghostly, incorporeal body dissipating into an ethereal mist of... of b-balls. I'm finally... coming... home...",1);
sCinema(oBarkley,"dialog","Dikembe! Wait! There's something I wanted to tell you!",1);
sCinema(oBaller,"dialog","Quickly Barkley, the b-ball curse has lifted!",1);
sCinema(oBarkley,"dialog","I... I'm sorry. I'm sorry about the Purge and I'm sorry about what happened.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBaller,"dialog","Barkley, I want you to carry on my legacy.",1);
sCinema(oBarkley,"dialog","What?",1);
sCinema(oBaller,"dialog","Close your eyes and let the power of jams wash over you. Let my knowledge enter your body...",1);
sCinema(oBarkley,"tint",c_white,1);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"tint",c_white,0);
sBattleSkill(0,"Holy Dunk");
sCinema(oBarkley,"dialog","Barkley has learned the forbidden jam \"Holy Dunk\"!");
sCinema(oBarkley,"dialog","Th-thank you, Dikembe!",1);
sCinema(oBaller,"dialog","You are welcome Barkley. Oh, and one last thing...",1);
sCinema(oBarkley,"dialog","Y-yes?",1);
sCinema(oBaller,"dialog","You are...",1);
sCinema(oBarkley,"tint",c_white,1);
sCinema(oBarkley,"wait",0.25);
sCinema(oBarkley,"code",cine_0186);
sCinema(oBarkley,"wait",0.25);
sCinema(oBarkley,"tint",c_white,0);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","...forgiven.");
sCinema(oBarkley,"wait",1);
sCinema(oBalthios,"dialog","We... We had better leave.",1);
sCinema(oCyberdwarf,"dialog","Yes... let's go.",1);
repeat (5) sCinema4(oBalthios,"move","down");
repeat (4) sCinema5(oCyberdwarf,"move","down");
repeat (4) sCinema6(inc,"move","down");
sCinema(oBarkley,"code",cine_0187);
repeat (2) sCinema(oBarkley,"move","down");
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"dialog","Goodbye... Dikembe. May you finally find your peace.",1);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomSewerTomb4;
}
