sA("stopall");
oRaffle.x=-999;
sOvar(object_index,3);
sOvar(oIntroL0,2);
sOvar(oLDoor1,2);
sOvar(oRaffle,1);
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"dialog","Huh? Where's Raffleson?",1);
sCinema(oFollower0,"dialog","This is odd. Maybe he caught word of our conversation in the cave and ran off?",1);
sCinema(oFollower2,"dialog","Let's not concern ourselves with this, he's gone and he can't touch Yelmirb if he's not here. No need to waste any more time, we should head to the tower.",1);
sCinema(oBarkley,"dialog","You're right, Liberty Tower it is.",1);
repeat (2) sCinema(oBarkley,"move","down");
sCinema(oBarkley,"code",cine_0389);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"dialog","Huh? Who locked the door?",1);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"code",cine_0390);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"wait",2);
sCinema(oFollower0,"dialog","Sugar gas particles are flooding this room, quick, find an escape before it poisons us all!",1);
sCinema(oBarkley,"move","left",6);
sCinema(oBarkley,"move","up",6);
sCinema(oBarkley,"face","down");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"move","right",6);
sCinema(oBarkley,"move","down",6);
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"code",cine_0391);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"wait",2);
sCinema(oFollower2,"dialog","It looks like the gas mechanism stalled... However we're still stuck in here.",1);
sCinema(oBarkley,"dialog","This is what Jenkins was probably talking about. Raffleson wanted to kill us before we got to him so he could get the sceptre. Looks like his master plan ran out of \"gas\".",1);
sCinema(oFollower0,"dialog","...",1);
sCinema(oFollower2,"dialog","...Let's just find a way out.",1);
//sCinema(oBarkley,'dialog',"Damnit don't look at me like that guys. I'm just trying to lighten the mood. Let's just find a way out.",1);
