if (sOvar(object_index,-1)=1) exit;
global.dialog=1;
oBarkley.move="";
sOvar(object_index,1);
sCinema(oBarkley,"code",cine_0084);
sCinema(oBarkley,"wait",1);
sCinema(oFollower2,"dialog","Th-that's the test subject we keep reading about!",1);
sCinema(oCagedBalla,"face","right");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"face","up");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"face","down");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"face","left");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"face","right");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"face","up");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"face","down");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"face","left");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"jump","start");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"jump","end");
sCinema(oCagedBalla,"face","up");
sCinema(oCagedBalla,"jump","start");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"jump","end");
sCinema(oCagedBalla,"face","right");
sCinema(oCagedBalla,"jump","start");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"jump","end");
sCinema(oCagedBalla,"face","down");
sCinema(oCagedBalla,"jump","start");
sCinema(oBarkley,"wait",0.3);
sCinema(oCagedBalla,"jump","end");
sCinema(oCagedBalla,"move","right");
sCinema(oBarkley,"wait",0.5);
sCinema(oCagedBalla,"face","up");
sCinema(oBarkley,"wait",0.5);
sCinema(oCagedBalla,"move","left");
sCinema(oCagedBalla,"move","left");
sCinema(oBarkley,"wait",0.5);
sCinema(oCagedBalla,"move","right");
sCinema(oCagedBalla,"face","down");
sCinema(oBarkley,"wait",0.3);
sCinema(oFollower0,"dialog","My god, that must be the prototype... look at his pivots, his slides. They're... They're-",1);
sCinema(oBarkley,"dialog","...perfect. I've only seen these kinds of jams one other time in my life.",1);
sCinema(oFollower0,"dialog","The Space Jam...",1);
sCinema(oBarkley,"dialog","Yes. I am positive that if this is indeed the prototype, it is the only tool capable of countering whatever B.L.O.O.D.M.O.S.E.S. has planned.",1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0085);
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"dialog","We're wasting time. We need to find this ball before it's too late.",1);
