global.skipper=16;
sCinema(oBarkley,"wait",1);
repeat (5) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",1);
sCinema(oHoopz,"dialog","I wonder what this place is. It seems kinda empty.",1);
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"wait",1);
sCinema(oHoopz,"dialog","Kinda boring... Hey, there's a switch over there! Maybe if I pull it the gate will open!",1);
repeat (5) sCinema(oBarkley,"move","up",4);
sCinema(oBarkley,"wait",0.5);
sCinema(oHoopz,"code",cine_0296);
sCinema(oBarkley,"wait",1);
sCinema(oHoopz,"code",cine_0297);
sCinema(oHoopz,"dialog","Wh-whoa! Sounds like the gate opened...",1);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomCuchBarkley0;
global.playersprite=sBarkley;
