if (sOvar(object_index,-1)=-1) { //224,112
sOvar(object_index,1);
with (oPlayer) indialog=1;
with (oFollower) x=-999;
oBarkley.t=3; oHoopz.t=3; oBalthios.t=3; oCyberdwarf.t=3;
oMalice.t=3;
oBalgord.t=3; oBalgord.x=224-4; oBalgord.y=112;
oWroth.t=0; oPelpoc.t=0; oZorf.t=0; oJamal.t=2;
global.nofollow=1;
sCinema(oBarkley,"cond",cine_0148);
sCinema(oBarkley,"code",cine_0074);
repeat (14) sCinema1(oHoopz,"move","left",4);
repeat (6) sCinema1(oHoopz,"move","up",4);
sCinema1(oHoopz,"face","left");
repeat (15) sCinema2(oCyberdwarf,"move","left",4);
repeat (4) sCinema2(oCyberdwarf,"move","up",4);
repeat (13) sCinema3(oBalthios,"move","left",4);
repeat (9) sCinema3(oBalthios,"move","up",4);
sCinema3(oBalthios,"face","left");
sCinema(oBarkley,"code",cine_0168);
repeat (15) sCinema(oBarkley,"move","left",4);
repeat (5) sCinema(oBarkley,"move","up",4);
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"dialog","Huh? What's going on here?",1);
sCinema(oBarkley,"wait",1);
sCinema(oJamal,"jump","start");
sCinema(oJamal,"jump","end");
sCinema(oBarkley,"dialog","Duergar Chieftan Jamal Bloodguzzle:\\We, as Duergars, can no longer tolerate the injustices put upon us by our genie captors. For too long have we allowed them and Square Enix Goya to force us to mine chups! No longer, I say! My father mined for rubies and gemstones, as did his father, and his father before him, and his before him, and so on. To be reduced to mining chups for genies... they'd be ashamed of us!");
sCinema(oZorf,"jump","start");
sCinema(oZorf,"jump","end");
sCinema(oBarkley,"dialog","Zorf Gobletwind:\\Here here!");
sCinema(oPelpoc,"jump","start");
sCinema(oPelpoc,"jump","end");
sCinema(oBarkley,"dialog","Pelpoc the Dire:\\What do you say we do, Jamal Bloodguzzle?");
sCinema(oBarkley,"dialog","Jamal Bloodguzzle:\\I say we go on strike and give these genies, who would disturb our right to accumulate treasure for our ghoulish Duergar gods, a piece of our minds!");
sCinema(oFred,"jump","start");
sCinema(oFred,"jump","end");
sCinema(oBarkley,"dialog","Fredegar Murderstone:\\Aye!");
sCinema(oWroth,"jump","start");
sCinema(oWroth,"jump","end");
sCinema(oBarkley,"dialog","Wrothgar Satchelscream:\\I'm with you!");
sCinema(oBarkley,"dialog","Jamal Bloodguzzle:\\We'll toil no longer for the genies until we can get a better contract; one that grants us all of the civil liberties that Duergars are entitled to!");
sCinema(oCyberdwarf,"dialog","It seems we've come to a Square Enix Goya-run mine that's run into a few labor problems.",1);
sCinema(oBalthios,"dialog","Perhaps we can find some way to help.",1);
sCinema(oBarkley,"dialog","You guys are always getting me dragged into shit I don't want nothing to do with. This is the every-man-for-himself Post-Cyberpocalypse, I don't have time for this shit. I don't even know what we could do to help.",1);
sCinema(oCyberdwarf,"dialog","These are Duergars, Barkley, my brethren. At least grant me the courtesy to visit them. It's been far too long since I have walked amongst the dwarfs...",1);
sCinema(oBarkley,"dialog","Fine, we can see what's up but I'm not getting involved in this shit.",1);
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0169);
sCinema(oBarkley,"tint",c_black,0);
} else {
event_user(3);
}
