with (oWall0) solid=0;
oSoldier1.t=1;
oSoldier2.t=1;
oSoldier3.t=1;
oSoldier4.t=1;
oSoldier5.t=1;
oSoldier6.t=1;
oCaptain0.t=1;
oHellbane.visible=1;
with (oBellwoman) instance_destroy();
with (oChupper) instance_destroy();
with (oSoldier0) instance_destroy();
with (oPunk1) instance_destroy();
with (oNobleguy0) instance_destroy();
with (oKid0) x=xstart-4;
with (oSoldier4) x=xstart-4; with (oSoldier1) x=xstart-4;
with (oSoldier2) x=xstart-4; with (oSoldier3) x=xstart-4;
with (oSoldier5) x=xstart-4; with (oSoldier6) x=xstart-4;
with (oCaptain0) x=xstart-4; with (oHellbane) x=xstart-4;
sCinema(oBarkley,"cond",cine_0148);
repeat(9) sCinema(oBarkley,"move","left",5);
sCinema(oBarkley,"dialog","G-god damnit!",1);
sCinema(oBarkley,"dialog","Soldier:\\Give yourself up, Barkley!");
sCinema(oBarkley,"dialog","No way in hell!",1);
sCinema1(oSoldier3,"hurt",oRaygun,oBarkley,-((16*2)+8));
sCinema1(oBarkley,"wait",0.5);
sCinema1(oBarkley,"move","down",5);
sCinema2(oBarkley,"jump","start");
sCinema2(oBarkley,"move","down",5);
sCinema2(oBarkley,"jump","end");
sCinema2(oSoldier3,"hurt",oRaygun,oDummy,-((16*11)+8));
if (global.scheme[8]!=2) {
sCinema(oBarkley,"quick","cancel");
sCinema(oBarkley,"code",cine_0269);
sCinema(oBarkley,"code",cine_0270);
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"cond",cine_0101);
} else {
repeat(7) sCinema(oKid0,"move","right",4);
repeat(7) sCinema7(oKid0,"move","left",5);
sCinema(oBarkley,"code",cine_0348);
sCinema(oSoldier1,"face","left");
sCinema(oSoldier2,"face","left");
sCinema(oSoldier3,"face","left");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"dialog","Soldier:\\Huh?! The damn kid stole my vintage Goya Cannon Mk II! After him!");
sCinema(oBarkley,"move","down",5);
}
repeat(17) sCinema(oBarkley,"move","down",5);
sCinema(oBarkley,"quick","up");
sCinema3(oBarkley,"code",cine_0093);
sCinema3(oBarkley,"wait",2);
sCinema3(oBarkley,"code",cine_0299);
sCinema3(oBarkley,"code",cine_0096);
sCinema3(oBarkley,"move","right",5);
sCinema3(oBarkley,"move","right",5);
sCinema3(oBarkley,"move","down",5);
sCinema3(oBarkley,"move","down",5);
sCinema3(oBarkley,"move","left",5);
sCinema3(oBarkley,"move","left",5);
sCinema4(oBarkley,"jump","start");
sCinema4(oBarkley,"move","down",5);
sCinema4(oBarkley,"move","down",5);
sCinema4(oBarkley,"jump","end");
sCinema(oBarkley,"code",cine_0271);
sCinema(oBarkley,"code",cine_0158);
sCinema(oBarkley,"cond",cine_0104);
sCinema(oBarkley,"cond",cine_0103);
sCinema(oBarkley,"move","down",5);
sCinema(oBarkley,"move","down",5);
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"dialog","Soldier:\\This is the end of the line, Barkley. You've got no choice but to surrender and tell us what you know about B.L.O.O.D.M.O.S.E.S.");
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"code",cine_0349);
repeat(4) sCinema(oJordan,"move","down");
sCinema(oJordan,"dialog","Barkley, this is your last chance to surrender and tell us everything you know about B.L.O.O.D.M.O.S.E.S. Think of your son...",1);
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"dialog","H-Hoopz... You wouldn't dare hurt him, Jordan! You god damned coward, you wouldn't dare hurt him!",1);
sCinema(oBarkley,"wait",1.1);
sCinema(oJordan,"face","up");
sCinema(oBarkley,"wait",1.1);
sCinema(oJordan,"dialog","Surrender... and it won't come to that.",1);
sCinema(oBarkley,"dialog","Okay... Okay... I'll give myse-",1);
sCinema(oBarkley,"dialog","???:\\Don't do it, Charles!");
sCinema5(oHellbane,"hurt",oSpitter,oSoldier6.x+12,oSoldier6.y+16);
sCinema6(oHellbane,"hurt",oSpitter,oSoldier5.x+12,oSoldier5.y+16);
sCinema(oBarkley,"code",cine_0350);
sCinema(oBarkley,"code",cine_0351);
sCinema(oHellbane,"hurt",oSpitter,oCaptain0.x+12,oCaptain0.y+16);
sCinema(oBarkley,"code",cine_0352);
sCinema(oBarkley,"code",cine_0353);
sCinema(oBarkley,"code",cine_0354);
sCinema(oJordan,"dialog","W-*what?");
sCinema(oBarkley,"dialog","???:\\Barkley, this way!");
repeat(12) sCinema(oHellbane,"move","right",8);
sCinema(oHellbane,"move","down",8);
repeat(17) sCinema(oHellbane,"move","right",8);
sCinema(oBarkley,"move","down",6);
sCinema(oBarkley,"move","down",6);
repeat(14) sCinema(oBarkley,"move","right",6);
repeat(3) sCinema(oJordan,"move","down");
sCinema(oJordan,"dialog","Damnit Barkley... You've gotten away this time... But you're a wanted man now. There won't be a next time.",1);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomCatacombMain;
