sPos("load");
oHoopzdummy.visible=1;
oHoopz.t=2;
sOvar(oLiberty,1);
sOvar(object_index,2);
with (oFollower) x=-999;
global.nofollow=1;
sCinema(oVince,"dialog","D-damnit...",1);
sCinema(oVince,"move","down");
sCinema(oBarkley,"wait",1);
sCinema(oVince,"move","down");
sCinema(oBarkley,"wait",1);
sCinema(oVince,"move","down",4);
sCinema(oVince,"move","down",4);
sCinema(oBarkley,"dialog","Are you guys okay?",1);
sCinema(oBalthios,"dialog","Y-yeah, I think I'm al-",1);
sCinema(oBarkley,"dialog","???:\\Dad?");
sCinema(oCyberdwarf,"face","up");
sCinema(oBalthios,"face","up");
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"code",cine_0384);
sCinema(oHoopz,"move","down");
sCinema(oBarkley,"dialog","H-Hoopz!",1);
sCinema(oHoopz,"face","right");
sCinema(oHoopz,"dialog","Dad, where am I? What's going on?",1);
sCinema(oBarkley,"dialog","Hoopz, I was so worried... I was so worried, Hoopz.",1);
sCinema(oHoopz,"dialog","What's going on? Where are we?",1);
sCinema(oBarkley,"dialog","L-let's go Hoopz. There are some things I need to tell you.",1);
sCinema(oHoopz,"dialog","Okay dad.",1);
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"code",cine_0385);
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"tint",c_black,0);
sCinema(oBarkley,"wait",2);
sCinema(oBrimley,"face","right");
sCinema(oBarkley,"wait",2);
sCinema(oBrimley,"move","down",5);
//sCinema(oBrimley,'move','down',5);
sCinema(oBarkley,"wait",3);
sCinema(oBrimley,"face","left");
sCinema(oBarkley,"wait",3);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomSubway1;
sA("stopall");
sA("loop",mCyberdwarf);
