sBoss("oBVince");
oVince.y+=32;
oHoopz.x=-999;
oBarkley.y=oBarkley.ystart;
oHoopzdummy.visible=0;
sOvar(object_index,1);
with (oFollower) x=-999;
global.nofollow=1;
repeat (2) sCinema1(oCyberdwarf,"move","up");
repeat (2) sCinema2(oBalthios,"move","up");
sCinema(oBarkley,"code",cine_0370);
repeat (2) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","Y... Yelmirb?",1);
sCinema(oBarkley,"wait",2);
sCinema(oBrimley,"dialog","???:\\You have come for something, haven't you?");
sCinema(oBarkley,"dialog","My son, Yelmirb, he's-",1);
sCinema(oBarkley,"dialog","???:\\That name... that name, it frustrates me. Do not call me that. Call me Brimley. Wilford Brimley.");
sCinema(oBarkley,"wait",1);
sCinema(oBrimley,"dialog","Speak, Charles Barkley. Tell me what it is you want from me. I do not have much time and only one gift left to give.",1);
sCinema(oBarkley,"dialog","H-how do you know my name?",1);
sCinema(oBarkley,"wait",1);
sCinema(oBrimley,"dialog","I know many things, Charles Barkley. Please, tell me about your son.",1);
sCinema(oBarkley,"dialog","They... That bastard, he...",1);
sCinema(oBrimley,"dialog","I sense a great level of diabetes within your son.",1);
sCinema(oBarkley,"dialog","It's... It's type 2, the kind they were never able to cure. I didn't know what to do, I didn't know where to take him. Please, Wilford Brimley, I need you.",1);
sCinema(oBarkley,"wait",2);
sCinema(oBrimley,"dialog","Many people need me, Charles Barkley, yet I can only help one. Do you know why I am hooked up to this machine? I have a gift. Perhaps others would call it a curse, but I choose to look at it differently. You see, I have the ability to take away someone's diabetes and make it my own. It hurts me, Charles Barkley, it hurts me very badly and because of the extremely high levels of diabetes in my body, I must remain connected to this insulin machine at all times. I have remained in this room for over fifty years absorbing the suffering of those around me, but my body has grown weak and not even the constant insulin drip of my machine can help me anymore... I am dying, Charles Barkley...   I am dying.",1);
sCinema(oBarkley,"wait",2);
sCinema(oBrimley,"dialog","Tell me, Charles Barkley... Why should I help you?",1);
sCinema(oBarkley,"dialog","I love my son.",1);
sCinema(oBrimley,"dialog","How much do you love him?",1);
sCinema(oBarkley,"wait",3);
sCinema(oBarkley,"dialog","More than I loved Maureen.",1);
sCinema(oBrimley,"dialog","That is all I wanted to hear. I will put Hoopz into my machine and I will take away his agony.",1);
repeat (2) sCinema(oBarkley,"move","up");
repeat (2) sCinema(oBarkley,"move","left");
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0386);
repeat (1) sCinema(oBarkley,"move","right");
sCinema(oBarkley,"dialog","???:\\Stop where you are!");
sCinema(oBarkley,"code",cine_0387);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"jump","start");
sCinema(oBalthios,"jump","start");
sCinema(oCyberdwarf,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oBalthios,"jump","end");
sCinema(oCyberdwarf,"jump","end");
repeat (4) sCinema(oVince,"move","up");
sCinema(oBarkley,"code",cine_0017);
sCinema(oBalthios,"dialog","Vinceborg!",1);
sCinema(oCyberdwarf,"dialog","Y-you son of a bitch! What the hell are you doing here!? What the hell do you want?",1);
sCinema(oVince,"dialog","My mission was to kill Hoopz Barkley. I am here to make sure that happens.",1);
sCinema(oBarkley,"dialog","God damnit, Vince! Snap out of it, don't you see you've been brainwashed by B.L.O.O.D.M.O.S.E.S.? This isn't like you, Vince! You're not one of the bad guys, you shouldn't be doing this!",1);
sCinema(oVince,"dialog","N-no, I shouldn-... This is not my concern. My mission is to kill Hoopz Barkley and if you're going to stand in my way, then I'll kill you too!",1);
sCinema(oBarkley,"code",cine_0380);
sCinema(oBarkley,"code",cine_0388);
sCinema(oBarkley,"code",cine_0006);
sA("stopall");
sA("loop",mCyberdwarf);
