sOvar(oIntro18,1);
oBarkley.t=0;
sCinema(oBarkley,"cond",cine_0148);
sCinema(oBarkley,"code",cine_0222);
//sCinema(oBarkley,'code',cine_0226);
repeat(5) sCinema(oBarkley,"move","up");
repeat(6) sCinema(oBarkley,"move","left");
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","What the hell is going on! What was that laughter? Who are you?",1);
sCinema(oBarkley,"dialog","???:\\Shhh! Quiet! He will hear us!");
sCinema(oBarkley,"dialog","Wh-who?",1);
sCinema(oBarkley,"dialog","???:\\The... Ghost Dad.");
sCinema(oBarkley,"dialog","Just tell me what the hell is going on here!",1);
sCinema(oBarkley,"dialog","???:\\K-keep it down! He's still here! Can't you hear him?");
sCinema(oBarkley,"code",cine_0227);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","???:\\Shit...");
sCinema(oBarkley,"wait",4);
sCinema(oBarkley,"dialog","???:\\I think... I think he's gone now. That was close. Charles, I haven't seen you in a long time.");
sCinema(oBarkley,"code",cine_0211);
sCinema(oBarkley,"dialog","What? I've never seen you in my life.",1);
sCinema(oBarkley,"dialog","???:\\You don't recognize my sensual curves and delicate frame, Charles Barkley? I was once the talk of the WNBA. Oh, but I suppose that the loose b-ball energies have ravaged my body and time has ravaged your memory.");
sCinema(oBarkley,"dialog","Ju... Juwanna? Juwanna Mann? It can't be you. You were one of the first killed in the Purge! What happened to you?",1);
sCinema(oJuwanna,"dialog","That's what the TVs said. I paid off those lousy reporters with what money I had left and went into hiding down here in Proto Neo New York... What I didn't know was that the b-ball energy levels down here were so high that all who were exposed became... b-ball mutants.",1);
sCinema(oBarkley,"dialog","Juwanna, I had no idea...",1);
sCinema(oJuwanna,"dialog","Nobody did. Not at first. But that's not even the worst of it.",1);
sCinema(oBarkley,"dialog","...the Ghost Dad.",1);
sCinema(oJuwanna,"dialog","I don't know who he is or where he came from, Charles, but he's terrible. He haunts the streets of Proto Neo New York looking for victims for his sadistic whims. We were already miserable, but before the Ghost Dad came, we could at least be miserable in peace.",1);
sCinema(oBarkley,"dialog","I'm really sorry, Juwanna Mann, but we're only here because we're on our way to the old Spalding building. We're not here to stay.",1);
sCinema(oJuwanna,"dialog","Heh, the old Spalding building. Want to relive your past glories, huh? That's a shame, Barkley.",1);
sCinema(oBarkley,"dialog","A shame? Why?",1);
sCinema(oJuwanna,"dialog","Because the old Spalding building's cut off by the fog. Don't even bother trying to stumble through that shit, you'll just get lost and wind up back here. Trust me, we've tried to reach it and... we lost a few men. It's because of the Ghost Dad, Charles. He's causing the mist, and I'm sure if you destroy him you can clear it out. Your only real option is to go into town and accept the hunter quest on the bulletin board to defeat the Ghost Dad and clear out the fog.",1);
sCinema(oBarkley,"dialog","Bulletin board? Hunter quest? What's all this?",1);
sCinema(oJuwanna,"dialog","Ask Ramirez. He's standing next to the hunter quest bulletin board and he's an expert. He can get you started out as a monster hunter.",1);
sCinema(oBarkley,"dialog","It looks like we've got no other choice. We'll accept the hunt quest and kill the Ghost Dad.",1);
sCinema(oJuwanna,"dialog","Thank you Charles... I mean it. Thank you.",1);
sCinema(oBarkley,"move","right");
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Don't think I'm doing it out of the kindness of my heart, Juwanna.",1);
sCinema(oBarkley,"code",cine_0228);
