sOvar(oSign1,1.9);
sOvar(oEvent0c,1);
sOvar(oEvent1c,1);
oBarkley.t=0;
sCinema(oBarkley,"cond",cine_0148);
sCinema(oBarkley,"code",cine_0222);
repeat(5) sCinema(oBarkley,"move","up");
repeat(8) sCinema(oBarkley,"move","left");
sCinema(oBarkley,"dialog","He's... gone, Juwanna Mann. The Ghost Dad is gone.",1);
sCinema(oJuwanna,"dialog","And so is the fog, Barkley.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oJuwanna,"move","right");
sCinema(oBarkley,"code",cine_0223);
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"code",cine_0224);
sCinema(oJuwanna,"dialog","Charles, I want to thank you for-",1);
sCinema(oBarkley,"move","right");
sCinema(oBarkley,"dialog","Juwanna, you know my heart still belongs to Maureen.",1);
sCinema(oJuwanna,"dialog","But we're both so lonely, you and I. I could make you happy again Charles. We could both be happy.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"dialog","I'm sorry, Juwanna, but I can't be happy knowing that somewhere out there, someone with the will and ability to perform another Chaos Dunk is alive. I can't sit still while people like B.L.O.O.D.M.O.S.E.S. plot to molest the world.",1);
sCinema(oJuwanna,"dialog","But... but why Charles? After all the world's done to you.",1);
sCinema(oBarkley,"dialog","What's the world done to me that I haven't deserved, Juwanna? I took b-ball for granted and when it was taken away from me, I realized how important it really was. That's why I'm doing this Juwanna. I'm not doing this for me. I'm not doing this for you or Maureen or the world. I'm doing this for Hoopz. I'm doing it so he can grow up in the same world I grew up in, a world where layups got you applause, not arrested. I'm doing this so he can know the same sport I did.",1);
sCinema(oJuwanna,"move","right");
sCinema(oBarkley,"wait",1);
sCinema(oJuwanna,"dialog","Charles...",1);
sCinema(oBarkley,"dialog","I'm sorry, Juwanna. Goodbye.",1);
//was 8 below
repeat(7) sCinema(oBarkley,"move","right",4);
repeat(4) sCinema(oBarkley,"move","down",4);
sCinema(oBarkley,"code",cine_0225);
sCinema(oBarkley,"wait",1);
sCinema(oJuwanna,"dialog","...goodbye Charles.",1);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomProtoStreet;
