//128,96
sOvar(oIntro17,1);
global.skipper=8;
global.nofollow=1;
with (oFollower) x=-999;
oHoopz.t=3;
oCyberdwarf.t=3;
oBalthios.t=3;
oBarkley.t=3;
oBarkley.x=288-4;
oBarkley.y=112;
sCinema(oBarkley,"tint",c_black,0.4);
sCinema(oBarkley,"cond",cine_0148);
repeat(3) sCinema1(oBalthios,"move","left");
repeat(3) sCinema2(oHoopz,"move","left");
repeat(3) sCinema3(oCyberdwarf,"move","left");
sCinema(oBarkley,"code",cine_0181);
repeat(3) sCinema(oBarkley,"move","left");
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","So this is... Proto Neo New York.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oHoopz,"dialog","Can... can we take a break dad? I'm getting kind of tired.",1);
sCinema(oBalthios,"dialog","I'll be the first to second that. My dogs are barkin', Charles.",1);
sCinema(oCyberdwarf,"dialog","I can keep going, but I still suggest we stop to gather our bearings and plan some things out.",1);
sCinema(oBarkley,"dialog","Alright...",1);
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0213);
sCinema(oBarkley,"code",cine_0214);
sCinema(oBarkley,"code",cine_0215);
sCinema(oBarkley,"code",cine_0216);
sCinema(oBarkley,"code",cine_0217);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"tint",c_black,0.4);
sCinema(oBarkley,"code",cine_0218);
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"dialog","Hoopz, I... I wanted you to know I'm sorry. I'm sorry for getting you involved in this whole mess, this whole goddamn mess.",1);
sCinema(oHoopz,"dialog","Dad, it's okay...",1);
sCinema(oBalthios,"dialog","It's best that we got Hoopz when we did. There's no telling what could have happened to him at the hands of Inspector Jordan and as much as I hate to say this, he's safer with us, despite the situation we're in.",1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"dialog","It's just... this is just all so bonkers. It's all so gatdam bonkers. All of this, we're running around the Post-Cyberpocalypse looking for clues about who or what B.L.O.O.D.M.O.S.E.S. is and who did the Chaos Dunk and all this shit about the Ultimate B-Ball. It's just... bonkers.",1);
sCinema(oBarkley,"move","down");
sCinema(oCyberdwarf,"dialog","As bonkers as it may be, Charles, the world hangs on a fringe and we're the only ones capable of saving it.",1);
sCinema(oBarkley,"dialog","You're right, Cyberdwarf. I know you are. I just wish shit didn't have to be this way. I wish it could just go back to when b-ball was b-ball with no shit attached and we didn't have to whisper every time we wanted to talk about Nike. It's like... the whole world's just fucked.",1);
sCinema(oBarkley,"wait",1.3);
sCinema(oHoopz,"dialog","Well maybe we can change that.",1);
sCinema(oBarkley,"dialog","Hoopz?",1);
sCinema(oHoopz,"dialog","Dad, I've been meaning to ask you... what's the Cyberpocalypse?",1);
sCinema(oBarkley,"dialog","Well Hoopz, I don't really know how to explain it to you. I'm not really a religious-",1);
sCinema(oCyberdwarf,"dialog","2000 years ago, a Jicklebergian freedom fighter was crucified by the British Empire in an event that is now known as the Boston Massacre. His name was... Clispaeth Ryuji Atuck.",1);
sCinema(oHoopz,"dialog","You mean... THE Clispaeth?",1);
sCinema(oCyberdwarf,"dialog","They are one and the same, Hoopz. It is shocking for many to give context to Clispaeth's historical relevance, but he was indeed real. He was the leader of an army that was fighting for the freedom of Jickleberg from the British Empire. The backlash of the Boston Massacre was tremendous; armies gathered underneath the banners of Clispaeth's remaining disciples to fight the British Empire. They fought. They fought for the duration of 666 years, until both sides were destroyed and the whole world obliterated. This was the Cyberpocalypse, and we are living in its consequences.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","The Clispaeth I learned about in church was-",1);
sCinema(oBarkley,"code",cine_0219);
sCinema(oBarkley,"wait",5.0);
sCinema(oBarkley,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oBarkley,"dialog","What the hell was that?",1);
sCinema(oBalthios,"face","left");
sCinema(oBarkley,"wait",0.5);
sCinema(oBalthios,"face","right");
sCinema(oBarkley,"wait",0.5);
sCinema(oBalthios,"face","left");
sCinema(oBarkley,"wait",0.5);
sCinema(oBalthios,"face","right");
sCinema(oBarkley,"wait",0.5);
sCinema(oBalthios,"face","left");
sCinema(oBarkley,"wait",0.5);
sCinema(oBarkley,"code",cine_0220);
sCinema(oBalthios,"dialog","That laughter... it's coming from over there!",1);
sCinema(oBarkley,"dialog","???:\\Quickly! Run into the house!");
//
sCinema(oBarkley,"jump","start");
sCinema(oBarkley,"jump","end");
sCinema(oBarkley,"dialog","Who's there?",1);
sCinema(oBarkley,"dialog","???:\\Do it or he'll get you! Quickly!");
sCinema(oBarkley,"dialog","I don't know what the hell is going on but we'd better do it.",1);
sCinema4(oBalthios,"move","left");
sCinema4(oBalthios,"move","up");
sCinema4(oBalthios,"move","up");
sCinema4(oBalthios,"move","up");
sCinema5(oHoopz,"move","left");
sCinema5(oHoopz,"move","up");
sCinema5(oHoopz,"move","up");
sCinema6(oCyberdwarf,"move","up");
sCinema6(oCyberdwarf,"move","left");
sCinema6(oCyberdwarf,"move","left");
sCinema6(oCyberdwarf,"move","left");
sCinema6(oCyberdwarf,"move","up");
sCinema(oBarkley,"code",cine_0187);
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"move","left");
sCinema(oBarkley,"move","left");
sCinema(oBarkley,"wait",.1);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomProtoJuwanna;
