sA("stopall");
sCinema(oCyberdwarf,"code",cine_0310);
sCinema(oCyberdwarf,"tint",c_black,1);
sCinema(oCyberdwarf,"wait",8);
sCinema(oCyberdwarf,"code",cine_0311);
sCinema(oCyberdwarf,"tint",c_black,0);
oHoopz.x=144-4;
oHoopz.y=96;
oCyberdwarf.t=0;
oHoopz.t=0;
oBalthios.x=-999;
oBarkley.x=-999;
oFollower.x=-999;
sCinema(oHoopz,"dialog","What was that sound, Cyberdwarf?",1);
sCinema(oCyberdwarf,"dialog","It... it was nothing, Hoopz.",1);
sCinema(oHoopz,"dialog","So dad's gonna be okay?",1);
sCinema(oCyberdwarf,"dialog","I hope so Hoopz. I truly do.",1);
sCinema(oCyberdwarf,"wait",1.5);
sCinema(oHoopz,"dialog","I miss him a little.",1);
sCinema(oCyberdwarf,"wait",1.5);
sCinema(oHoopz,"dialog","Where are we going, Cyberdwarf?",1);
sCinema(oCyberdwarf,"dialog","I'm... not sure yet. Perhaps we're going home. Perhaps we're going home to a new world.",1);
sCinema(oHoopz,"dialog","A new world...",1);
sCinema(oCyberdwarf,"effect","fadein",3);
global.roz=RomCredits;
