oBalthios.t=3;
oBarkley.x+=8;
global.nofollow=1;
global.skipper=24;
with (oFollower) x=-999;
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0017);
sCinema(oBalthios,"dialog","This... this is it, Barkley.",1);
sCinema(oBarkley,"dialog","Hmm?",1);
sCinema(oBalthios,"dialog","This is gonna be the final battle. There's no turning back from here.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oHoopz,"dialog","Are they gonna give us back b-ball, dad?",1);
sCinema(oBarkley,"dialog","I... I don't know Hoopz.",1);
sCinema(oHoopz,"dialog","I just hope that when we get rid of this Ultimate B-Ball thing, they realize that it's not b-ball that's the problem, but the people who misuse it. Basketball's not about hurting people. It's about slamming and jamming, right dad?",1);
sCinema(oBarkley,"dialog","Yeah, Hoopz... yeah.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oCyberdwarf,"dialog","We're approaching the Necron 5. I don't know what we to expect once we're inside so everyone be on high alert.",1);
sCinema(oBarkley,"dialog","Cyberdwarf, can you come here a second?",1);
sCinema(oCyberdwarf,"dialog","Okay...",1);
repeat (5) sCinema(oCyberdwarf,"move","down");
sCinema(oCyberdwarf,"move","left");
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"wait",.8);
sCinema(oBarkley,"dialog","Cyberdwarf... if anything happens to me, I want you to take care of him.",1);
sCinema(oCyberdwarf,"dialog","Barkley, I don't know if I can do that. My basketball skin makes me ill-equipped to be a father.",1);
sCinema(oBarkley,"dialog","I'm not asking you to be a father, Cyberdwarf. I'm asking you to be a mentor.",1);
sCinema(oCyberdwarf,"dialog","If anything happens to you, yes, I will take care of Hoopz.",1);
sCinema(oBarkley,"dialog","Thank you, Cyberdwarf.",1);
sCinema(oBarkley,"wait",.3);
sCinema(oCyberdwarf,"move","right");
repeat (5) sCinema(oCyberdwarf,"move","up");
sCinema(oBarkley,"wait",1);
sCinema(oCyberdwarf,"dialog","Prepare for entry into Necron 5...",1);
sCinema(oBarkley,"code",cine_0312);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomNecronEnter;
