global.skipper=17;
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Huh, what's this? An empty room?",1);
repeat (8) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"face","left");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"face","right");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"face","up");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"dialog","Totally empty except for this-",1);
sCinema(oBarkley,"code",cine_0304);
sCinema(oBarkley,"wait",.8);
sCinema(oBarkley,"dialog","Wh-what was that?",1);
sCinema(oBarkley,"face","down");
sCinema(oBarkley,"dialog","G-gold...",1);
sCinema(oBarkley,"move","down");
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"dialog","Incan gold...",1);
sCinema(oBarkley,"dialog","???:\\Take it, Barkley. Take the Incan gold. You want it, Barkley. You want it more than anything else.");
sCinema(oBarkley,"dialog","I... I want the Incan gold...",1);
sCinema(oBarkley,"dialog","???:\\Touch it. Touch the gold, Barkley. Touch the Incan gold.");
sCinema(oBarkley,"dialog","I probably should...",1);
repeat (3) sCinema(oBarkley,"move","down",4);
sCinema(oBarkley,"code",cine_0305);
sCinema(oBarkley,"cond",cine_0306);
sCinema(oBarkley,"dialog","???:\\HAHAHAHA, you fool, Charles Barkley! You have freed me! You have freed me from my millenia of imprisonment!");
sCinema(oBarkley,"wait",2);
sCinema(oBarkley,"dialog","Oh shit.",1);
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"dialog","Did I just free Cuchulainn?",1);
sCinema(oBarkley,"dialog","The Incan gold wasn't even real...",1);
repeat (4) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",1.3);
sCinema(oBarkley,"dialog","I should probably pull this switch...",1);
sCinema(oBarkley,"code",cine_0296);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0297);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomCuchSplit;
global.playersprite=sBarkley;
