global.skipper=7;
global.b_music=mBattle;
sFollow("delete",oFollower1);
sOvar(oIntro11,1);
oLarry.face=15;
oLarry.y-=32;
oVince.t=2;
oHoopz.t=2;
oJordan.t=2;
oCyberdwarf.t=0;
oBalthios.t=0;
oBarkley.t=0;
oBarkley.y-=7*16;
oCyberdwarf.y-=10*16;
oCyberdwarf.x+=16;
oVince.x=oJordan.x-16;
oVince.y=oJordan.y+32;
oHoopz.y-=16;
oBalthios.y-=10*16;
global.plot=8;
global.nofollow=1;
with (oFollower) x=-999;
sCinema(oLarry,"code",cine_0188);
sCinema(oJordan,"dialog","You... You son of a bitch, Barkley.",1);
sCinema(oBarkley,"dialog","Get the fuck away from him!",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","DO IT, JORDAN!",1);
sCinema(oJordan,"dialog","You won today, Barkley. Yeah, you beat me. Fucking gloat. But I'll get you Barkley. I'll get you and the rest of you god damned sportlovers and when I do, you'll fucking bleed Gatorade to your graves.",1);
sCinema(oJordan,"move","down");
repeat (4) sCinema(oJordan,"move","right",4);
sCinema(oJordan,"move","up",4);
repeat (3) sCinema(oJordan,"move","right",4);
repeat (3) sCinema(oJordan,"move","up",4);
sCinema(oBarkley,"code",cine_0189);
sCinema(oVince,"dialog","Mission: failed. Retreat to B.L.O.O.D.M.O.S.E.S. for reconstruction process and second attempt.",1);
repeat (5) sCinema(oVince,"move","right");
sCinema(oBalthios,"dialog","Vince, wait!",1);
sCinema(oVince,"dialog","I am no longer Vince Carter, Balthios... I am Vinceborg 2050, B.L.O.O.D.M.O.S.E.S. agent of death.",1);
repeat (2) sCinema(oVince,"move","up");
repeat (3) sCinema(oVince,"move","right");
repeat (3) sCinema(oVince,"move","up");
sCinema(oBarkley,"code",cine_0190);
sCinema(oBarkley,"dialog","Damnit Vince... Damnit...",1);
sCinema(oHoopz,"dialog","Dad!",1);
sCinema(oBarkley,"dialog","I'm... I'm here son.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","???|Larry Bird:\\B...arkl...ey...");
sCinema(oBarkley,"dialog","L-Larry?",1);
sCinema(oBarkley,"move","right");
repeat (5) sCinema(oBarkley,"move","up",4);
sCinema(oLarry,"dialog","I... I did everything I could for Hoopz...",1);
sCinema(oBarkley,"dialog","Larry, don't talk. You'll reopen your wounds...",1);
sCinema(oLarry,"dialog","I'm dead anyways, Barkley. Jordan got me good.",1);
sCinema(oBarkley,"dialog","Larry...",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oLarry,"dialog","I wanted to tell you I was sorry, Barkley.",1);
sCinema(oBarkley,"dialog","Sorry?",1);
sCinema(oLarry,"dialog","For that... that argument we had earlier. You were right...",1);
sCinema(oBarkley,"dialog","Larry, you don't need to-",1);
sCinema(oLarry,"dialog","I had no right to say the things that I did... How did we grow so apart, Charles? We used to be so close... I... I knew it wasn't you who did that Chaos Dunk in Manhattan, Charles.",1);
sCinema(oBarkley,"dialog","How do you know?",1);
sCinema(oLarry,"dialog","Look at yourself, Barkley. You wouldn't hurt a fly, not after what happened to Maureen...",1);
sCinema(oBarkley,"wait",1.2);
sCinema(oLarry,"dialog","It's getting cold, Charles... It's getting so...",1);
sCinema(oBarkley,"wait",1.7);
sCinema(oBarkley,"dialog","Goodbye, Larry.",1);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomSewerCyberhome;
