global.dialog=1;
itemf[0]="Battlestech Gun";
itemf[1]="Dwarfstear";
itemf[2]="Mystic B-ball";
itemf[3]="Ecto Cooler";
itemf[4]="BBall Shard";
itemf[5]="Steroids";
itemf[6]="Goggles";
itemf[7]="Athletic Supporter";
itemf[8]="Referee Uniform";
itemf[9]="Tek-Skeleton";
itemf[10]="";
sCinema(oBarkley,"dialog","Tron:\\You guys interested in anything?");
sCinema(oBarkley,"code",cine_0482);
sCinema(oBarkley,"cond",cine_0003);
sCinema(oBarkley,"dialog","Tron:\\You on your way to Liberty Island?");
sCinema(oBarkley,"dialog","Yeah, that's where we're headed. We don't have much time to get there.",1);
sCinema(oBarkley,"dialog","Tron:\\You guys pilgrims?");
sCinema(oBarkley,"dialog","Pilgrims?",1);
sCinema(oBarkley,"dialog","Tron:\\Didn't think so, you guys don't look like those people. Cultists or whatever, I don't know. They come here every once in a while and I can make business but you can tell just by looking at them that something's wrong with them. Like they just don't have enough insulin or something. It's creepy.");
sCinema(oBarkley,"dialog","Thanks a lot man.",1);
sCinema(oBarkley,"dialog","Tron:\\Yeah, you take care.");
