global.skipper=15;
sCinema(oBarkley,"wait",1.5);
//sCinema(oBarkley,'move','up');
sCinema(oCyberdwarf,"dialog","Hmm, I wonder what this room is.",1);
repeat (5) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",1);
sCinema(oCyberdwarf,"dialog","What is this? A... a dwarf?",1);
sCinema(oBarkley,"move","right"); sCinema(oBarkley,"move","up"); sCinema(oBarkley,"face","left"); sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"move","up"); sCinema(oBarkley,"move","left"); sCinema(oBarkley,"face","down"); sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"move","left"); sCinema(oBarkley,"move","down"); sCinema(oBarkley,"face","right"); sCinema(oBarkley,"wait",.5);
sCinema(oBarkley,"move","down"); sCinema(oBarkley,"move","right"); sCinema(oBarkley,"face","up"); sCinema(oBarkley,"wait",.5);
sCinema(oCyberdwarf,"dialog","Is this... me? Is this who I would have been if...",1);
sCinema(oBarkley,"wait",1);
sCinema(oCyberdwarf,"dialog","M-my skin... I've been so lonely since the accident, nobody will talk to a... to a gatdam dwarf with b-ball skin. All these years and not a single friend, not a single lover to make the pain go away, if only for one night. Nobody ever said "+"\"Hey Cyberdwarf, how is it going\" or \"Cyberdwarf, I love you\""+". Nobody. And... and it's because of my appearance. This... is who I should have been.",1);
sCinema(oCyberdwarf,"dialog","???:\\This is who you can be if only you touch the image.");
sCinema(oCyberdwarf,"dialog","I... I can become him if I touch it?",1);
sCinema(oCyberdwarf,"dialog","???:\\You no longer need to wear the shackles of b-ball skin, Cyberdwarf. You no longer need to feel the pain of being alone.");
sCinema(oBarkley,"wait",1.5);
sCinema(oCyberdwarf,"dialog","Hmph. I'm not so vain and foolish as to believe you, Cuchulainn. I wear my b-ball skin with pride. I hold my head high and proudly call myself a B-Ball American. I honor the traditions of the b-balls that came before me and I will continue to do so.",1);
sCinema(oBarkley,"move","right");
repeat (5) sCinema(oBarkley,"move","up");
sCinema(oCyberdwarf,"dialog","Now all I need to do is hit this switch.",1);
sCinema(oCyberdwarf,"code",cine_0296);
sCinema(oBarkley,"wait",1);
sCinema(oCyberdwarf,"code",cine_0297);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomCuchHoop0;
global.playersprite=sHoopz0;

