sOvar(object_index,3);
global.char_eweapon[4]="ZX Zaubertech1";
global.nofollow=1;
with (oFollower) x=-999;
oBalthios.x=oBalthios.xstart-4;
oCyberdwarf.x=oCyberdwarf.xstart-4;
oHoopz.x=oHoopz.xstart-4;
oJuwanna.x=oJuwanna.xstart-4;
oJuwanna.y-=16;
oBarkley.t=2;
oHoopz.t=3;
oCyberdwarf.t=1;
oBalthios.t=0;
//sItem("Turkey Feather",-1);
sCinema(oBarkley,"cond",cine_0148);
sCinema(oHoopz,"dialog","D-dad...",1);
sCinema(oBarkley,"dialog","I don't know what it means, son. I don't know why you were the only one to survive, but I believe there's a reason. You wouldn't have been born in an egg if there wasn't a reason. You wouldn't have survived the Chaos Dunk if there wasn't a reason. You're special, Hoopz. You can't deny it.",1);
sCinema(oCyberdwarf,"dialog","Whether your differences are a blessing or a curse have yet to be proven, Hoopz, but I believe that whatever lies ahead of us is waiting for you.",1);
sCinema(oHoopz,"dialog","You mean like... ~F.A.T.E.~?",1);
sCinema(oCyberdwarf,"dialog","Perhaps...",1);
sCinema(oBarkley,"dialog","???:\\Charles!");
sCinema(oBarkley,"code",cine_0316);
sCinema(oBarkley,"dialog","Wh-what?",1);
sCinema(oBarkley,"wait",1);
repeat (7) sCinema(oJuwanna,"move","down");
sCinema(oJuwanna,"dialog","Charles... I... I followed you here.",1);
sCinema(oBarkley,"dialog","J-Juwanna Mann?",1);
sCinema(oJuwanna,"dialog","I needed you to know, Charles that... that I love you with all my heart and bones.",1);
sCinema(oBarkley,"dialog","Juwanna...",1);
sCinema(oBarkley,"wait",1);
sCinema(oJuwanna,"dialog","I have something for you. It's a whistle. A Dimension Whistle to be exact. One toot on this will send you to the B-Ball Dimension. I... I don't know how it works but you can use it wherever you want and it only works once.",1);
sCinema(oBarkley,"dialog","J-Juwanna, I... Thank you.",1);
sCinema(oJuwanna,"dialog","No Charles. Thank you.",1);
sCinema(oBarkley,"item","Dimension Whistle",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","Juwanna, there's... there's something I want to give you.",1);
sCinema(oJuwanna,"dialog","Y-yes?",1);
sCinema(oBarkley,"dialog","This turkey feather belonged to Maureen. It means a lot to me, Juwanna Mann. I want you to have it.",1);
sCinema(oJuwanna,"dialog","Charles, I can't.",1);
sCinema(oBarkley,"dialog","Juwanna, please... Take it.",1);
sCinema(oBarkley,"code",cine_0317);
sCinema(oBarkley,"dialog","Lose Zalatar's Precious Turkey Feather!");
sCinema(oJuwanna,"dialog","Thank you Charles. Will I ever see you again?",1);
sCinema(oBarkley,"dialog","I don't know, Juwanna. We're looking for manufacted jamicite and we don't know where to start.",1);
sCinema(oJuwanna,"dialog","I'd check Cuchulainn's Tomb if I were you. I've heard there's a large cache of it there. Do you know how to get there?",1);
sCinema(oBarkley,"dialog","Not really.",1);
sCinema(oJuwanna,"dialog","You'll have to take the Underground Railroad to get there. It's just down the steps, just talk to the conductor.",1);
sCinema(oBarkley,"dialog","Juwanna.",1);
sCinema(oJuwanna,"dialog","Y-yes?",1);
sCinema(oBarkley,"dialog","...goodbye.",1);
sCinema(oJuwanna,"dialog","Goodbye, Charles... Goodbye.",1);
repeat (7) sCinema(oJuwanna,"move","up");
sCinema(oBarkley,"face","down");
sCinema(oBalthios,"dialog","What was that, Barkley? Are you in love?",1);
sCinema(oBarkley,"dialog","You know I couldn't do that to Maureen, Balthios. Grow up.",1);
sCinema(oBalthios,"dialog","Hahaha, you act tough but you fall for them easily, you know that?",1);
sCinema(oBarkley,"dialog","I said-",1);
sCinema(oCyberdwarf,"dialog","Enough! We have very little time to get to Cuchulainn's Tomb to get the manufacted jamicite. We need to speak to the conductor of the Underground Railroad immediately.",1);
sCinema(oBarkley,"dialog","Right, we can't waste anymore time. Come on, guys.",1);
sCinema(oBarkley,"tint",c_black,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0318);
sCinema(oBarkley,"code",cine_0319);
sCinema(oBarkley,"tint",c_black,0);
