sOvar(oIntro11,1);
sBoss("JordanVince");
sItem(global.char_eweapon[2],1);
sItem(global.char_earmour[2],1);
sItem(global.char_eaccess[2],1);
oLarry.y-=32;
oVince.t=0;
oHoopz.t=2;
oJordan.t=2;
oCyberdwarf.t=0;
oBalthios.t=0;
oBarkley.t=0;
global.nofollow=1;
with (oFollower) x=-999;
sCinema(oLarry,"code",cine_0188);
repeat (9) sCinema1(oBalthios,"move","up");
repeat (8) sCinema2(oCyberdwarf,"move","up");
sCinema2(oCyberdwarf,"move","right");
sCinema2(oCyberdwarf,"move","up");
repeat (8) sCinema3(oVince,"move","up");
sCinema3(oVince,"move","left");
sCinema3(oVince,"move","up");
sCinema(oBarkley,"code",cine_0181);
repeat (9) sCinema(oBarkley,"move","up");
sCinema(oBarkley,"wait",1.5);
sCinema(oJordan,"dialog","Hahaha, I knew you'd come back for him, Barkley. I knew I could count on your sense of family to bring you back. That's just like you, Barkley. Everyone around you is your own little family you can always count on. Well not me, Barkley. I wasn't a part of your little... 'b-ball family'. Heh, I was the black sheep of your god damn Barkley b-ball clique.",1);
sCinema(oBarkley,"dialog","Put the gun down and let him go, Jordan!",1);
sCinema(oJordan,"dialog","Or you'll do what? You're a fucking coward, Barkley. You wouldn't put your son's life in danger like that. No, you're one of those fucking goodie two-shoes, always looking out for someone else and never yourself. I guess you just snapped, huh? Just let it all go when you did that Chaos Dunk. Just like that, Barkley. Like a twig. You just snapped and killed all those people, didn't you? Did b-ball really mean that much to you?",1);
sCinema(oBarkley,"dialog","You shut the fuck up and let him go, Jordan!",1);
sCinema(oHoopz,"dialog","Dad!",1);
sCinema(oJordan,"dialog","Shut up you little shit, or I'll pump you with lead like I did to Bird.",1);
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"dialog","L-Larry! What did you do to Larry!?",1);
sCinema(oJordan,"dialog","I didn't do anything to him, Barkley. It was you. If you hadn't Chaos Dunked Manhattan, I wouldn't have had to blow him away. It's your fault.",1);
sCinema(oBalthios,"dialog","You... You sick son of a bitch, Jordan. If you so much as lay a hand on-",1);
sCinema(oJordan,"dialog","Shut the fuck up! I've got you where I want you, Barkley! I've got you by the nuts, you motherfucking sportlover! First I'm gonna ice you, then I'm gonna ice this little shit at my feet!",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oHoopz,"move","up");
sCinema(oBarkley,"wait",1.5);
sCinema(oJordan,"dialog","What the fuck are you doing, you little shit?",1);
sCinema(oHoopz,"dialog","I'm... I'm praying to Clispaeth, Mr. Jordan...",1);
sCinema(oJordan,"dialog","Cl-Clispaeth?",1);
sCinema(oCyberdwarf,"move","up");
sCinema(oCyberdwarf,"dialog","Clispaeth?\\(Can it really be? Is he... the one?)",1);
sCinema(oVince,"dialog","The...\\One...\\The... One...\\The... One...",1);
sCinema(oBalthios,"dialog","V-vinceborg?",1);
sCinema(oVince,"move","up");
sCinema(oVince,"dialog","M-memories are... flooding back. The one... The... one...",1);
sCinema(oJordan,"dialog","What the fuck is this? Is this a fucking joke?",1);
sCinema(oVince,"move","up");
sCinema(oVince,"move","up");
sCinema(oVince,"dialog","My mission was to... it was... to destroy... the one.",1);
sCinema(oBarkley,"code",cine_0191);
sCinema(oVince,"dialog","Vinceborg has left the party!");
sCinema(oCyberdwarf,"dialog","Vinceborg, no!",1);
sCinema(oVince,"dialog","Must destroy... Hoopz Barkley.",1);
sCinema(oVince,"move","up");
sCinema(oVince,"face","down");
sCinema(oBarkley,"dialog","That's it! Fuck this, you're going down, Jordan!",1);
sCinema(oBarkley,"code",cine_0192);
sCinema(oBarkley,"code",cine_0006);
