if (sOvar(oEventL6,-1)=1) exit;
global.dialog=1;
oBarkley.move="";
sBoss("oBReginald");
sOvar(oEventL6,1); //752,288
repeat (6) sCinema(oBarkley,"move","down");
sCinema(oBarkley,"code",cine_0017);
sCinema(oBarkley,"dialog","The Diabeastie!",1);
sCinema(oBarkley,"dialog","Diabeastie?:\\...");
sCinema(oFollower2,"dialog","It's holding the rod. We're going to have to slay this beast.",1);
sCinema(oBarkley,"dialog","Diabeastie?:\\Then it's a good thing I am not the Diabeastie.");
sCinema(oBarkley,"dialog","What? You can talk?",1);
sCinema(oDiabeastfake,"move","down");
sCinema(oBarkley,"dialog","Diabeastie?:\\Perhaps you will recognize me without the disguise...");
sCinema(oDiabeastfake,"effect","swap",sCult2);
sCinema(oBarkley,"wait",2);
sCinema(oFollower0,"dialog","Richards? You were the Diabeastie this whole time?",1);
sCinema(oBarkley,"dialog","Reginald:\\Richards is such an old name... I prefer the title Reginald, to be frank.");
sCinema(oBarkley,"dialog","Enough with the name games, chump. Hand over the rod.",1);
sCinema(oBarkley,"dialog","Reginald:\\You don't understand do you? The evil you are commiting...");
sCinema(oDiabeastfake,"move","up");
sCinema(oDiabeastfake,"move","up");
sCinema(oBarkley,"dialog","Reginald:\\Did you ever think for a second why they wanted to exile me?");
sCinema(oBarkley,"dialog","I had enough of you fruit cakes and your gatdam tales already! Just hand over the rod!",1);
sCinema(oFollower0,"dialog","Barkley, we need to hear him out. It would be irresponsible to pass judgement otherwise.",1);
sCinema(oBarkley,"dialog","He tried to kill us. Good enough reason for me.",1);
sCinema(oBarkley,"dialog","Reginald:\\I did not know I could trust you... I also apologize for my actions, but I believed a greater good would be accomplished. You see, I did have a radical belief according to the plebeians inhabiting this island. I believed we should clone Yelmirb, so that we could rid diabetes once and for all. They let \"morals\" cloud their judgement and said it would be inhumane, creating someone to absorb the suffering of others. But who would have to know? Is it not better for one man to carry the burden than society as a whole? They call this killing Yelmirb, I call it rebirth.");
sCinema(oFollower2,"dialog","You can't make a decision like that. It's not yours to make.",1);
sCinema(oBarkley,"dialog","Reginald:\\How dare you speak in such tone when you desire Yelmirb's service. Do you think he says some magick words, and mystically takes away the diabetes from your son? No. He absorbs it, so your son does not have to live a crippled life. Yelmirb understands his sacrifices to humanity. Subsequent clones would as well.");
sCinema(oFollower0,"dialog","You can't play Clispaeth. No one can. You're deranged.",1);
sCinema(oBarkley,"dialog","Reginald:\\Very well. I see you are as ignorant as those who lived on this island... No matter! Fear my deadly magicks!");
sCinema(oBarkley,"code",cine_0074);
sCinema(oBarkley,"code",cine_0130);
sCinema(oBarkley,"code",cine_0131);
sCinema(oBarkley,"code",cine_0006);
//sCinema(oBarkley,'effect','fadein',3);
//global.roz=RomLibertyWell;
