oMack.solid=0;
oMack.x-=8;
oMack.y-=1;
sBoss("oBDiabeasty");
oSteambrast.visible=0;
sOvar(oMack,5);
repeat (8) sCinema(oBarkley,"move","up",4);
sCinema(oBarkley,"dialog","Mack:\\Back off Diabeastie! You will find no satisfaction in destroying our lands!",0);
sCinema(oBarkley,"dialog","Diabeastie:\\Sugar SuGar SUGaR sugaR.",0);
sCinema(oDiabeastie,"move","up");
sCinema(oDiabeastie,"move","right");
sCinema(oDiabeastie,"move","up");
sCinema(oDiabeastie,"move","right");
sCinema(oDiabeastie,"move","up");
sCinema(oBarkley,"dialog","Diabeastie:\\<GLOMP>",0);
sCinema(oBarkley,"code",cine_0379);
sCinema(oBarkley,"dialog","Mack:\\Noooo! Gahhhhhh!",0);
sCinema(oFollower0,"dialog","So the tomes were right... It does exist.",1);
sCinema(oBarkley,"move","up");
sCinema(oBarkley,"dialog","He's just a chump like any other. Hey Diabeastie! Over here!",1);
sCinema(oDiabeastie,"move","down");
sCinema(oDiabeastie,"move","right");
sCinema(oDiabeastie,"move","down");
sCinema(oBarkley,"dialog","Diabeastie:\\SUGAR SUgAR!",0);
sCinema(oBarkley,"dialog","Game on punk!",1);
sCinema(oBarkley,"code",cine_0380);
sCinema(oBarkley,"code",cine_0381);
sCinema(oBarkley,"code",cine_0006);
