global.skipper=13;
with (oFollower) x=-999;
global.nofollow=1;
sFollow("delete",oFollower0);
sFollow("delete",oFollower2);
sFollow("delete",oFollower3);
sOvar(object_index,1);
sCinema(oBarkley,"wait",1);
sCinema(oBarkley,"code",cine_0180);
sCinema(oBarkley,"code",cine_0178);
sCinema(oBarkley,"code",cine_0295);
repeat (10) sCinema(oBarkley,"move","up");
repeat (9) sCinema1(oBalthios,"move","up");
sCinema1(oBalthios,"move","left");
sCinema1(oBalthios,"face","right");
repeat (8) sCinema2(oCyberdwarf,"move","up");
repeat (8) sCinema3(oHoopz,"move","up");
sCinema3(oHoopz,"move","right");
sCinema3(oHoopz,"face","left");
sCinema(oBarkley,"cond",cine_0102);
sCinema(oBarkley,"cond",cine_0101);
sCinema(oBarkley,"cond",cine_0103);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","What's this? It looks like the way is blocked.",1);
sCinema(oCyberdwarf,"dialog","It is, Barkley. The jamicite we're looking for is on the other side of this door.",1);
sCinema(oBarkley,"dialog","Well that doesn't help us. How the hell are we going to get this gatdam door open?",1);
sCinema(oBalthios,"dialog","Barkley, calm down! Not in front of Hoopz!",1);
sCinema(oHoopz,"dialog","D-dad...",1);
sCinema(oBarkley,"move","down");
sCinema(oBarkley,"dialog","I'm... I'm sorry, I lost my temper and I shouldn't have but there's just... so much at stake. We can't afford to fuck up.",1);
sCinema(oHoopz,"dialog","It's okay dad, it's just... sometimes I get scared when you're like this.",1);
sCinema(oBarkley,"wait",1.5);
sCinema(oBarkley,"dialog","We're gonna need to find a way to open this door someway or another.",1);
sCinema(oBalthios,"dialog","Well there seem to be four corridors leading from this gateway. It would be logical if we split up, one to each corridor, and looked for a way to open it.",1);
sCinema(oCyberdwarf,"dialog","It sounds like a good plan. We'll cover more ground that way. Is this alright with you, Barkley?",1);
sCinema(oBarkley,"dialog","It looks like we don't have much of a choice. I'll take the top right path. Balthios and Hoopz can take the bottom paths and Cyberdwarf can take the top left one.",1);
sCinema(oCyberdwarf,"dialog","We'll need to hustle, we don't have much time left. Oh and... good luck everyone.",1);
sCinema(oBarkley,"code",cine_0014);
sCinema(oBarkley,"effect","fadein",3);
global.roz=RomCuchBalthios0;
global.playersprite=sBalthios;
